global.torch = 0
surface_light = -4
surface_rain = -4
meteo_alpha = 0
meteo_alpha_max = 0.4
meteo_alpha_increase = 0.005
ciclo_now = (1 << 0)
color_surface = 16777215
darkness_max = 1
darkness_now = 0
var a = (0 << 0)
ciclo_time[a] = 6
ciclo_color[a] = 2429720
a = (1 << 0)
ciclo_time[a] = 9
ciclo_color[a] = 16777215
a = (2 << 0)
ciclo_time[a] = 18
ciclo_color[a] = 2429720
a = (3 << 0)
ciclo_time[a] = 21
ciclo_color[a] = 2429720
day_name[(1 << 0)] = "Monday"
day_name[(2 << 0)] = "Tuesday"
day_name[(3 << 0)] = "Wednesday"
day_name[(4 << 0)] = "Thursday"
day_name[(5 << 0)] = "Friday"
day_name[(6 << 0)] = "Saturday"
day_name[(7 << 0)] = "Sunday"
day_now = (1 << 0)
time_increase = 0.3
time_second = 0
second = 0
minute = 0
hour = 2
day = 1
month = 1
year = 2018
ini_open(global.save_general)
minute = ini_read_real("Time", "Minutes", 0)
hour = ini_read_real("Time", "Hour", 10)
day = ini_read_real("Time", "Day", 1)
month = ini_read_real("Time", "Month", 1)
year = ini_read_real("Time", "Year", 2018)
day_now = ini_read_real("Time", "Day_now", (1 << 0))
real_time_played = ini_read_real("Real time played", "seconds", 0)
real_time_step = 0
ini_close()
pos_center = shader_get_uniform(shd_night_vision_hud, "pos_center")
