function scr_indoor_oil_medium_3(argument0, argument1, argument2, argument3) //gml_Script_scr_indoor_oil_medium_3
{
    var xx = argument0
    var yy = argument1
    var dest_x = argument2
    var dest_y = argument3
    var o = obj_map_generator
    scr_place_obj_map(104, ((xx * 16) + 282), ((yy * 16) + 137))
    scr_place_obj_map(104, ((xx * 16) + 285), ((yy * 16) + 82))
    scr_place_obj_map(104, ((xx * 16) + 275), ((yy * 16) + 74))
    scr_place_obj_map(137, ((xx * 16) + 208), ((yy * 16) + 128))
    scr_place_obj_map(137, ((xx * 16) + 240), ((yy * 16) + 144))
    scr_place_obj_map(138, ((xx * 16) + 288), ((yy * 16) + 144))
    scr_place_obj_map(138, ((xx * 16) + 288), ((yy * 16) + 112))
    scr_place_obj_map(171, ((xx * 16) + 272), ((yy * 16) + 64))
    scr_place_obj_map(120, ((xx * 16) + 70), ((yy * 16) + 42))
    scr_place_obj_map(118, ((xx * 16) + 80), ((yy * 16) + 28))
    scr_place_obj_map(116, ((xx * 16) + 56), ((yy * 16) + 49))
    scr_place_obj_map(116, ((xx * 16) + 40), ((yy * 16) + 49))
    scr_place_obj_map(116, ((xx * 16) + 24), ((yy * 16) + 49))
    scr_place_obj_map(116, ((xx * 16) + 24), ((yy * 16) + 49))
    scr_place_obj_map(121, ((xx * 16) + 48), ((yy * 16) + 62))
    scr_place_obj_map(121, ((xx * 16) + 32), ((yy * 16) + 62))
    scr_place_obj_map(121, ((xx * 16) + 16), ((yy * 16) + 62))
    scr_place_obj_map(122, ((xx * 16) + 48), ((yy * 16) + 46))
    scr_place_obj_map(122, ((xx * 16) + 32), ((yy * 16) + 46))
    scr_place_obj_map(122, ((xx * 16) + 16), ((yy * 16) + 46))
    scr_place_obj_map(129, ((xx * 16) + 297), ((yy * 16) + 275))
    scr_place_obj_map(129, ((xx * 16) + 202), ((yy * 16) + 239))
    scr_place_obj_map(132, ((xx * 16) + 192), ((yy * 16) + 230))
    scr_place_obj_map(126, ((xx * 16) + 279), ((yy * 16) + 245))
    scr_place_obj_map(126, ((xx * 16) + 280), ((yy * 16) + 214))
    scr_place_obj_map(126, ((xx * 16) + 25), ((yy * 16) + 245))
    scr_place_obj_map(126, ((xx * 16) + 25), ((yy * 16) + 213))
    scr_place_obj_map(126, ((xx * 16) + 25), ((yy * 16) + 185))
    scr_place_obj_map(23, ((xx * 16) + 283), ((yy * 16) + 304))
    scr_place_obj_map(23, ((xx * 16) + 275), ((yy * 16) + 304))
    scr_place_obj_map(23, ((xx * 16) + 243), ((yy * 16) + 215))
    scr_place_obj_map(23, ((xx * 16) + 19), ((yy * 16) + 278))
    scr_place_obj_map(23, ((xx * 16) + 91), ((yy * 16) + 231))
    scr_place_obj_map(23, ((xx * 16) + 204), ((yy * 16) + 197))
    scr_place_obj_map(137, ((xx * 16) + 240), ((yy * 16) + 304))
    scr_place_obj_map(138, ((xx * 16) + 288), ((yy * 16) + 304))
    scr_place_obj_map(135, ((xx * 16) + 272), ((yy * 16) + 240))
    scr_place_obj_map(135, ((xx * 16) + 272), ((yy * 16) + 208))
    scr_place_obj_map(137, ((xx * 16) + 240), ((yy * 16) + 208))
    scr_place_obj_map(137, ((xx * 16) + 48), ((yy * 16) + 176))
    scr_place_obj_map(138, ((xx * 16) + 80), ((yy * 16) + 224))
    scr_place_obj_map(138, ((xx * 16) + 80), ((yy * 16) + 192))
    scr_place_obj_map(136, ((xx * 16) + 16), ((yy * 16) + 304))
    scr_place_obj_map(135, ((xx * 16) + 16), ((yy * 16) + 240))
    scr_place_obj_map(135, ((xx * 16) + 16), ((yy * 16) + 208))
    scr_place_obj_map(135, ((xx * 16) + 16), ((yy * 16) + 176))
    instance_create_depth(((xx * 16) + 280), ((yy * 16) + 102), 0, obj_chest_attachment)
    instance_create_depth(((xx * 16) + 89), ((yy * 16) + 64), 0, obj_chest_bag)
    instance_create_depth(((xx * 16) + 73), ((yy * 16) + 186), 0, obj_chest_electronic_box)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 64), 0, obj_chest_cabinet)
    instance_create_depth(((xx * 16) + 240), ((yy * 16) + 64), 0, obj_chest_cabinet)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 64), 0, obj_chest_cabinet)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 64), 0, obj_chest_cabinet)
    instance_create_depth(((xx * 16) + 184), ((yy * 16) + 191), 0, obj_chest_vending_machine)
    instance_create_depth(((xx * 16) + 200), ((yy * 16) + 191), 0, obj_chest_vending_machine)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 240), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 40), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 40), 0, obj_solid)
    instance_create_depth(((xx * 16) + 240), ((yy * 16) + 40), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 40), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 288), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 288), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 240), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 169), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 169), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 169), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 240), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 288), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 240), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 288), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 240), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 304), 0, obj_solid)
    var o_indoor = instance_create_depth(((xx * 16) + 153), ((yy * 16) + 284), 0, obj_indoor)
    o_indoor.tele_x = dest_x
    o_indoor.tele_y = dest_y
    var o_indoor2 = instance_create_depth((x + o.b_x[decor_id][image_index]), (y + o.b_y[decor_id][image_index]), 0, obj_indoor)
    o_indoor2.tele_x = (((xx * 16) + 8) + 153)
    o_indoor2.tele_y = (((yy * 16) + 5) + 284)
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 1), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 1), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 1), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 335, (xx + 1), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 2), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 2), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 2), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 2), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 3), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 3), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 3), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 3), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 261, (xx + 3), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 335, (xx + 4), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 4), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 4), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 4), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 261, (xx + 4), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 261, (xx + 4), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 335, (xx + 5), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 5), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 5), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 332, (xx + 5), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 261, (xx + 7), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 261, (xx + 9), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 261, (xx + 9), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 261, (xx + 10), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 524, (xx + 11), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 588, (xx + 11), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 261, (xx + 11), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 526, (xx + 12), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 590, (xx + 12), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 366, (xx + 12), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 261, (xx + 16), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 261, (xx + 16), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 261, (xx + 17), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 261, (xx + 17), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 334, (xx + 18), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 261, (xx + 18), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 18))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 1), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 1), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 1), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 1), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 497, (xx + 1), (yy + 16))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 2), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 2), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 462, (xx + 2), (yy + 4))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 2), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 2), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 529, (xx + 2), (yy + 15))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 3), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 3), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 3), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 3), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 533, (xx + 3), (yy + 11))
    tilemap_set(o.layer_tileset_wall_below_indoor, 530, (xx + 3), (yy + 12))
    tilemap_set(o.layer_tileset_wall_below_indoor, 534, (xx + 3), (yy + 18))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 4), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 4), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 529, (xx + 4), (yy + 5))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 4), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 4), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 533, (xx + 4), (yy + 15))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 5), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 5), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 5), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 5), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 529, (xx + 5), (yy + 17))
    tilemap_set(o.layer_tileset_wall_below_indoor, 104, (xx + 6), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 136, (xx + 6), (yy + 4))
    tilemap_set(o.layer_tileset_wall_below_indoor, 104, (xx + 6), (yy + 13))
    tilemap_set(o.layer_tileset_wall_below_indoor, 136, (xx + 6), (yy + 14))
    tilemap_set(o.layer_tileset_wall_below_indoor, 105, (xx + 7), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 7), (yy + 4))
    tilemap_set(o.layer_tileset_wall_below_indoor, 105, (xx + 7), (yy + 13))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 7), (yy + 14))
    tilemap_set(o.layer_tileset_wall_below_indoor, 105, (xx + 8), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 8), (yy + 4))
    tilemap_set(o.layer_tileset_wall_below_indoor, 106, (xx + 8), (yy + 13))
    tilemap_set(o.layer_tileset_wall_below_indoor, 138, (xx + 8), (yy + 14))
    tilemap_set(o.layer_tileset_wall_below_indoor, 105, (xx + 9), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 9), (yy + 4))
    tilemap_set(o.layer_tileset_wall_below_indoor, 533, (xx + 9), (yy + 5))
    tilemap_set(o.layer_tileset_wall_below_indoor, 534, (xx + 9), (yy + 11))
    tilemap_set(o.layer_tileset_wall_below_indoor, 468, (xx + 9), (yy + 12))
    tilemap_set(o.layer_tileset_wall_below_indoor, 534, (xx + 9), (yy + 16))
    tilemap_set(o.layer_tileset_wall_below_indoor, 105, (xx + 10), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 10), (yy + 4))
    tilemap_set(o.layer_tileset_wall_below_indoor, 469, (xx + 10), (yy + 13))
    tilemap_set(o.layer_tileset_wall_below_indoor, 105, (xx + 11), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 11), (yy + 4))
    tilemap_set(o.layer_tileset_wall_below_indoor, 104, (xx + 11), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 136, (xx + 11), (yy + 10))
    tilemap_set(o.layer_tileset_wall_below_indoor, 465, (xx + 11), (yy + 12))
    tilemap_set(o.layer_tileset_wall_below_indoor, 106, (xx + 12), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 138, (xx + 12), (yy + 4))
    tilemap_set(o.layer_tileset_wall_below_indoor, 105, (xx + 12), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 12), (yy + 10))
    tilemap_set(o.layer_tileset_wall_below_indoor, 498, (xx + 12), (yy + 16))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 13), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 13), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 493, (xx + 13), (yy + 4))
    tilemap_set(o.layer_tileset_wall_below_indoor, 104, (xx + 13), (yy + 13))
    tilemap_set(o.layer_tileset_wall_below_indoor, 136, (xx + 13), (yy + 14))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 14), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 14), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 527, (xx + 14), (yy + 5))
    tilemap_set(o.layer_tileset_wall_below_indoor, 106, (xx + 14), (yy + 13))
    tilemap_set(o.layer_tileset_wall_below_indoor, 138, (xx + 14), (yy + 14))
    tilemap_set(o.layer_tileset_wall_below_indoor, 502, (xx + 14), (yy + 15))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 15), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 15), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 15), (yy + 10))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 15), (yy + 11))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 16), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 16), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 533, (xx + 16), (yy + 4))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 16), (yy + 10))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 16), (yy + 11))
    tilemap_set(o.layer_tileset_wall_below_indoor, 533, (xx + 16), (yy + 13))
    tilemap_set(o.layer_tileset_wall_below_indoor, 528, (xx + 16), (yy + 15))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 17), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 17), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 462, (xx + 17), (yy + 6))
    tilemap_set(o.layer_tileset_wall_below_indoor, 533, (xx + 17), (yy + 7))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 17), (yy + 10))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 17), (yy + 11))
    tilemap_set(o.layer_tileset_wall_below_indoor, 534, (xx + 17), (yy + 17))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 18), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 18), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 18), (yy + 10))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 18), (yy + 11))
    tilemap_set(o.layer_tileset_wall_below_indoor, 494, (xx + 18), (yy + 15))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 200, (xx + 0), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 168, (xx + 0), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 15))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 200, (xx + 0), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 1), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 1), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 1), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 1), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 2), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 2), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 2), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 2), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 3), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 3), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 3), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 3), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 4), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 4), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 4), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 4), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 5), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 5), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 5), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 5), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 169, (xx + 6), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 6), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 72, (xx + 6), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 6), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 169, (xx + 6), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 6), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 6), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 6), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 6), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 72, (xx + 6), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 8, (xx + 6), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 6), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 201, (xx + 6), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 7), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 7), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 7), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 10, (xx + 7), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 200, (xx + 7), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 8), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 10, (xx + 8), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 8), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 8), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 8), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 8), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 8), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 74, (xx + 8), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 10, (xx + 8), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 200, (xx + 8), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 9), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 9), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 10), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 10), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 11), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 8, (xx + 11), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 11), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 72, (xx + 11), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 8, (xx + 11), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 201, (xx + 11), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 168, (xx + 12), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 12), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 74, (xx + 12), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 10, (xx + 12), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 200, (xx + 12), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 12), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 12), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 13), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 13), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 169, (xx + 13), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 13), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 13), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 13), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 72, (xx + 13), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 8, (xx + 13), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 201, (xx + 13), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 14), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 10, (xx + 14), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 200, (xx + 14), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 168, (xx + 14), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 14), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 14), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 74, (xx + 14), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 10, (xx + 14), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 14), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 200, (xx + 14), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 15), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 15), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 15), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 15), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 16), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 16), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 16), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 16), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 17), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 17), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 17), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 17), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 18), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 18), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 18), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 18), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 169, (xx + 19), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 201, (xx + 19), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 169, (xx + 19), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 15))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 19), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 201, (xx + 19), (yy + 18))
    return;
}

