state = (0 << 0)
var a = (0 << 0)
tutorial_name[a] = "Movement"
t_x1[a] = 274
t_y1[a] = 520
t_x2[a] = 385
t_y2[a] = 661
tutorial_text[a] = "Use W,A,S,D to move.\nHold Lshift while moving to run. Running should be use only when you are in danger, get caught by an enemy while having no stamina will probably get you killed."
a = (1 << 0)
tutorial_name[a] = "Inventory managment"
t_x1[a] = 385
t_y1[a] = 520
t_x2[a] = 608
t_y2[a] = 661
tutorial_text[a] = "Press TAB to open the inventory.\nDrag the equipment to the corrispondent box to equip.\nDrag medical items to quick slot's box, in this way you can use them without open the inventory.\nYou can manually use an item while you are in the inventory by Left click on it and use it.\nYou can discard items by dragging them to the discard grid.\nPress F near a chest to open it, drag items in your inventory to loot them.\nHold Lctrl and press LMB on a item will move it quickly to the other grid.\nDrag an item and then holding Lctrl will split the amount.\nPress F near an NPC to talk with him."
a = (2 << 0)
tutorial_name[a] = "Combat"
t_x1[a] = 608
t_y1[a] = 480
t_x2[a] = 945
t_y2[a] = 690
tutorial_text[a] = "Press LMB to shoot.\nMove while shooting will decrease your accuracy and increase recoil.\nIf you have a scoped weapon press RMB to aim, shoot while aiming grant 100% accuracy, no bullet travel time and more damage.\nWeapons and armor have durability, shoot and getting hitted by an enemy will decrease the durability.\nLess durability means less damage, accuracy and more recoil for weapons while less protection for armor.\nUse a repair kit to repair weapons and armor."
a = (3 << 0)
tutorial_name[a] = "Personal Device"
t_x1[a] = 945
t_y1[a] = 464
t_x2[a] = 1136
t_y2[a] = 690
tutorial_text[a] = "Press J to open your personal device provived by the Crimson Corporation.\nFrom the left side:\nMap menu: you can see the map and eventually task location.\nTask menu: you can see the tasks status.\nLevel menu: see your level and your stats.\nSkill tree menu: unlock new skill.\nFaction menu: each faction has different relation with others. This affect NPC behavior during the game."
a = (4 << 0)
tutorial_name[a] = "Last"
t_x1[a] = 1136
t_y1[a] = 464
t_x2[a] = 1283
t_y2[a] = 690
tutorial_text[a] = "The tutorial is complete! It's short because these are the essential information you need to play.\nOnce you have started the game go and talk to the Barman, he will tell you how to proceed.\nPress ESC and go to main menu to exit."
