function scr_indoor_factory_small_3(argument0, argument1, argument2, argument3) //gml_Script_scr_indoor_factory_small_3
{
    var xx = argument0
    var yy = argument1
    var dest_x = argument2
    var dest_y = argument3
    var o = obj_map_generator
    scr_place_obj_map(111, ((xx * 16) + 129), ((yy * 16) + 101))
    scr_place_obj_map(111, ((xx * 16) + 147), ((yy * 16) + 121))
    scr_place_obj_map(111, ((xx * 16) + 128), ((yy * 16) + 135))
    scr_place_obj_map(111, ((xx * 16) + 110), ((yy * 16) + 118))
    scr_place_obj_map(106, ((xx * 16) + 128), ((yy * 16) + 128))
    scr_place_obj_map(104, ((xx * 16) + 137), ((yy * 16) + 203))
    scr_place_obj_map(104, ((xx * 16) + 87), ((yy * 16) + 189))
    scr_place_obj_map(104, ((xx * 16) + 199), ((yy * 16) + 197))
    scr_place_obj_map(104, ((xx * 16) + 187), ((yy * 16) + 87))
    scr_place_obj_map(104, ((xx * 16) + 193), ((yy * 16) + 106))
    scr_place_obj_map(104, ((xx * 16) + 197), ((yy * 16) + 141))
    scr_place_obj_map(101, ((xx * 16) + 138), ((yy * 16) + 80))
    scr_place_obj_map(101, ((xx * 16) + 119), ((yy * 16) + 72))
    scr_place_obj_map(101, ((xx * 16) + 105), ((yy * 16) + 66))
    scr_place_obj_map(101, ((xx * 16) + 98), ((yy * 16) + 76))
    scr_place_obj_map(101, ((xx * 16) + 137), ((yy * 16) + 67))
    scr_place_obj_map(101, ((xx * 16) + 88), ((yy * 16) + 68))
    scr_place_obj_map(105, ((xx * 16) + 212), ((yy * 16) + 121))
    scr_place_obj_map(105, ((xx * 16) + 216), ((yy * 16) + 148))
    scr_place_obj_map(105, ((xx * 16) + 187), ((yy * 16) + 71))
    scr_place_obj_map(105, ((xx * 16) + 161), ((yy * 16) + 78))
    scr_place_obj_map(105, ((xx * 16) + 209), ((yy * 16) + 96))
    scr_place_obj_map(105, ((xx * 16) + 213), ((yy * 16) + 72))
    scr_place_obj_map(111, ((xx * 16) + 63), ((yy * 16) + 195))
    scr_place_obj_map(111, ((xx * 16) + 72), ((yy * 16) + 174))
    scr_place_obj_map(111, ((xx * 16) + 62), ((yy * 16) + 117))
    scr_place_obj_map(111, ((xx * 16) + 73), ((yy * 16) + 140))
    scr_place_obj_map(108, ((xx * 16) + 63), ((yy * 16) + 191))
    scr_place_obj_map(108, ((xx * 16) + 63), ((yy * 16) + 143))
    scr_place_obj_map(110, ((xx * 16) + 24), ((yy * 16) + 116))
    scr_place_obj_map(144, ((xx * 16) + 40), ((yy * 16) + 199))
    scr_place_obj_map(140, ((xx * 16) + 40), ((yy * 16) + 196))
    scr_place_obj_map(140, ((xx * 16) + 40), ((yy * 16) + 180))
    scr_place_obj_map(140, ((xx * 16) + 40), ((yy * 16) + 164))
    scr_place_obj_map(140, ((xx * 16) + 40), ((yy * 16) + 148))
    scr_place_obj_map(140, ((xx * 16) + 40), ((yy * 16) + 132))
    scr_place_obj_map(140, ((xx * 16) + 40), ((yy * 16) + 116))
    scr_place_obj_map(150, ((xx * 16) + 32), ((yy * 16) + 96))
    scr_place_obj_map(151, ((xx * 16) + 16), ((yy * 16) + 80))
    instance_create_depth(((xx * 16) + 72), ((yy * 16) + 96), 0, obj_chest_tool_box)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 41), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 41), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 208), 0, obj_solid)
    var o_indoor = instance_create_depth(((xx * 16) + 160), ((yy * 16) + 192), 0, obj_indoor)
    o_indoor.tele_x = dest_x
    o_indoor.tele_y = dest_y
    var o_indoor2 = instance_create_depth((x + o.b_x[decor_id][image_index]), (y + o.b_y[decor_id][image_index]), 0, obj_indoor)
    o_indoor2.tele_x = (((xx * 16) + 8) + 160)
    o_indoor2.tele_y = (((yy * 16) + 5) + 192)
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 1), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 1), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 1), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 1), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 1), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 1), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 1), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 334, (xx + 1), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 334, (xx + 1), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 334, (xx + 1), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 2), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 2), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 2), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 2), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 2), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 2), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 2), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 2), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 2), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 2), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 3), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 3), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 3), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 367, (xx + 3), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 399, (xx + 3), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 399, (xx + 3), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 431, (xx + 3), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 3), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 3), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 3), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 4), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 4), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 4), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 368, (xx + 4), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 4), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 4), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 432, (xx + 4), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 4), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 4), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 4), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 5), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 5), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 5), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 368, (xx + 5), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 5), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 5), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 432, (xx + 5), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 5), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 5), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 5), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 6), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 6), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 6), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 368, (xx + 6), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 6), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 6), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 432, (xx + 6), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 6), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 6), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 6), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 7), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 7), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 7), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 368, (xx + 7), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 7), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 7), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 432, (xx + 7), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 7), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 7), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 7), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 8), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 8), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 8), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 368, (xx + 8), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 8), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 8), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 432, (xx + 8), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 8), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 8), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 8), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 9), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 9), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 9), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 369, (xx + 9), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 401, (xx + 9), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 401, (xx + 9), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 433, (xx + 9), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 9), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 9), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 9), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 10), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 10), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 10), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 10), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 10), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 10), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 10), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 10), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 10), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 430, (xx + 10), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 11), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 11), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 11), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 11), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 11), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 11), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 11), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 11), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 11), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 11), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 12), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 12), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 12), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 12), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 12), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 12), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 12), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 12), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 12), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 12), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 13), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 366, (xx + 13), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 366, (xx + 13), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 366, (xx + 13), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 398, (xx + 14), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 279, (xx + 1), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 1), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 248, (xx + 2), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 2), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 248, (xx + 3), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 3), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 248, (xx + 4), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 4), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 248, (xx + 5), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 5), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 343, (xx + 6), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 375, (xx + 6), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 376, (xx + 6), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 343, (xx + 7), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 375, (xx + 7), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 376, (xx + 7), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 343, (xx + 8), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 375, (xx + 8), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 376, (xx + 8), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 343, (xx + 9), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 375, (xx + 9), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 376, (xx + 9), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 248, (xx + 10), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 10), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 248, (xx + 11), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 11), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 280, (xx + 12), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 12), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 120, (xx + 13), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 13), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 183, (xx + 0), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 215, (xx + 0), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 0), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 0), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 1), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 1), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 1), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 1), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 2), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 2), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 2), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 2), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 3), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 3), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 3), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 3), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 4), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 4), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 4), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 4), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 5), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 5), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 5), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 5), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 6), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 6), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 6), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 6), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 7), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 7), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 7), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 7), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 8), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 8), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 8), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 8), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 9), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 25, (xx + 9), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 9), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 9), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 10), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 10), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 10), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 11), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 23, (xx + 11), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 11), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 11), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 12), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 12), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 12), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 12), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 13), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 13), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 13), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 13), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 184, (xx + 14), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 216, (xx + 14), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 14), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 14), (yy + 14))
    return;
}

