if ds_exists(grid_radiation, 5)
    ds_grid_destroy(grid_radiation)
if ds_exists(grid_tile, 5)
    ds_grid_destroy(grid_tile)
if ds_exists(grid_building, 5)
    ds_grid_destroy(grid_building)
if ds_exists(grid_floor2, 5)
    ds_grid_destroy(grid_floor2)
if ds_exists(grid_strada, 5)
    ds_grid_destroy(grid_strada)
if ds_exists(grid_map, 5)
    ds_grid_destroy(grid_map)
if ds_exists(grid_train, 5)
    ds_grid_destroy(grid_train)
if ds_exists(grid_parking, 5)
    ds_grid_destroy(grid_parking)
if ds_exists(grid_marciapiede, 5)
    ds_grid_destroy(grid_marciapiede)
if ds_exists(grid_water, 5)
    ds_grid_destroy(grid_water)
if ds_exists(grid_fence, 5)
    ds_grid_destroy(grid_fence)
if ds_exists(grid_indoor, 5)
    ds_grid_destroy(grid_indoor)
if ds_exists(grid_light_indoor, 5)
    ds_grid_destroy(grid_light_indoor)
if surface_exists(surface_floor2)
    surface_free(surface_floor2)
