function scr_indoor_oil_small_3(argument0, argument1, argument2, argument3) //gml_Script_scr_indoor_oil_small_3
{
    var xx = argument0
    var yy = argument1
    var dest_x = argument2
    var dest_y = argument3
    var o = obj_map_generator
    scr_place_obj_map(101, ((xx * 16) + 53), ((yy * 16) + 86))
    scr_place_obj_map(101, ((xx * 16) + 57), ((yy * 16) + 75))
    scr_place_obj_map(101, ((xx * 16) + 73), ((yy * 16) + 69))
    scr_place_obj_map(101, ((xx * 16) + 107), ((yy * 16) + 106))
    scr_place_obj_map(101, ((xx * 16) + 102), ((yy * 16) + 97))
    scr_place_obj_map(101, ((xx * 16) + 109), ((yy * 16) + 89))
    scr_place_obj_map(101, ((xx * 16) + 99), ((yy * 16) + 79))
    scr_place_obj_map(101, ((xx * 16) + 89), ((yy * 16) + 72))
    scr_place_obj_map(101, ((xx * 16) + 106), ((yy * 16) + 68))
    scr_place_obj_map(156, ((xx * 16) + 16), ((yy * 16) + 112))
    scr_place_obj_map(156, ((xx * 16) + 16), ((yy * 16) + 96))
    scr_place_obj_map(156, ((xx * 16) + 16), ((yy * 16) + 80))
    scr_place_obj_map(49, ((xx * 16) + 96), ((yy * 16) + 32))
    scr_place_obj_map(49, ((xx * 16) + 96), ((yy * 16) + 48))
    scr_place_obj_map(49, ((xx * 16) + 64), ((yy * 16) + 48))
    scr_place_obj_map(49, ((xx * 16) + 64), ((yy * 16) + 32))
    scr_place_obj_map(49, ((xx * 16) + 32), ((yy * 16) + 32))
    scr_place_obj_map(49, ((xx * 16) + 32), ((yy * 16) + 48))
    scr_place_obj_map(48, ((xx * 16) + 80), ((yy * 16) + 48))
    scr_place_obj_map(48, ((xx * 16) + 48), ((yy * 16) + 48))
    scr_place_obj_map(48, ((xx * 16) + 16), ((yy * 16) + 48))
    scr_place_obj_map(48, ((xx * 16) + 80), ((yy * 16) + 32))
    scr_place_obj_map(48, ((xx * 16) + 48), ((yy * 16) + 32))
    scr_place_obj_map(48, ((xx * 16) + 16), ((yy * 16) + 32))
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 32), 0, obj_solid)
    var o_indoor = instance_create_depth(((xx * 16) + 64), ((yy * 16) + 96), 0, obj_indoor)
    o_indoor.tele_x = dest_x
    o_indoor.tele_y = dest_y
    var o_indoor2 = instance_create_depth((x + o.b_x[decor_id][image_index]), (y + o.b_y[decor_id][image_index]), 0, obj_indoor)
    o_indoor2.tele_x = (((xx * 16) + 8) + 64)
    o_indoor2.tele_y = (((yy * 16) + 5) + 96)
    tilemap_set(o.layer_tileset_floor_indoor, 388, (xx + 0), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 420, (xx + 0), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 389, (xx + 7), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 421, (xx + 7), (yy + 6))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 1), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 1), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 202, (xx + 2), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 2), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 3), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 3), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 4), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 4), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 202, (xx + 5), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 5), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 170, (xx + 6), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 137, (xx + 6), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 168, (xx + 0), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 42, (xx + 0), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 200, (xx + 0), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 0), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 1), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 1), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 1), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 2), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 2), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 2), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 3), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 3), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 3), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 4), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 4), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 4), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 5), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 5), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 5), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 73, (xx + 6), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 9, (xx + 6), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 6), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 169, (xx + 7), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 7), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 7), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 7), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 7), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 40, (xx + 7), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 201, (xx + 7), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 7), (yy + 7))
    return;
}

