function scr_indoor_factory_small_1(argument0, argument1, argument2, argument3) //gml_Script_scr_indoor_factory_small_1
{
    var xx = argument0
    var yy = argument1
    var dest_x = argument2
    var dest_y = argument3
    var o = obj_map_generator
    scr_place_obj_map(82, ((xx * 16) + 41), ((yy * 16) + 152))
    scr_place_obj_map(82, ((xx * 16) + 61), ((yy * 16) + 203))
    scr_place_obj_map(123, ((xx * 16) + 25), ((yy * 16) + 173))
    scr_place_obj_map(123, ((xx * 16) + 38), ((yy * 16) + 81))
    scr_place_obj_map(123, ((xx * 16) + 217), ((yy * 16) + 195))
    scr_place_obj_map(23, ((xx * 16) + 184), ((yy * 16) + 59))
    scr_place_obj_map(104, ((xx * 16) + 37), ((yy * 16) + 69))
    scr_place_obj_map(104, ((xx * 16) + 165), ((yy * 16) + 72))
    scr_place_obj_map(104, ((xx * 16) + 42), ((yy * 16) + 59))
    scr_place_obj_map(104, ((xx * 16) + 54), ((yy * 16) + 63))
    scr_place_obj_map(104, ((xx * 16) + 84), ((yy * 16) + 62))
    scr_place_obj_map(104, ((xx * 16) + 75), ((yy * 16) + 56))
    scr_place_obj_map(104, ((xx * 16) + 67), ((yy * 16) + 65))
    scr_place_obj_map(101, ((xx * 16) + 21), ((yy * 16) + 130))
    scr_place_obj_map(101, ((xx * 16) + 20), ((yy * 16) + 95))
    scr_place_obj_map(101, ((xx * 16) + 23), ((yy * 16) + 142))
    scr_place_obj_map(101, ((xx * 16) + 25), ((yy * 16) + 104))
    scr_place_obj_map(101, ((xx * 16) + 23), ((yy * 16) + 122))
    scr_place_obj_map(101, ((xx * 16) + 25), ((yy * 16) + 87))
    scr_place_obj_map(111, ((xx * 16) + 57), ((yy * 16) + 119))
    scr_place_obj_map(111, ((xx * 16) + 69), ((yy * 16) + 100))
    scr_place_obj_map(111, ((xx * 16) + 125), ((yy * 16) + 103))
    scr_place_obj_map(111, ((xx * 16) + 145), ((yy * 16) + 108))
    scr_place_obj_map(111, ((xx * 16) + 120), ((yy * 16) + 118))
    scr_place_obj_map(111, ((xx * 16) + 198), ((yy * 16) + 89))
    scr_place_obj_map(111, ((xx * 16) + 204), ((yy * 16) + 126))
    scr_place_obj_map(110, ((xx * 16) + 216), ((yy * 16) + 175))
    scr_place_obj_map(110, ((xx * 16) + 216), ((yy * 16) + 111))
    scr_place_obj_map(108, ((xx * 16) + 216), ((yy * 16) + 143))
    scr_place_obj_map(107, ((xx * 16) + 128), ((yy * 16) + 112))
    scr_place_obj_map(107, ((xx * 16) + 64), ((yy * 16) + 112))
    scr_place_obj_map(109, ((xx * 16) + 160), ((yy * 16) + 64))
    scr_place_obj_map(106, ((xx * 16) + 208), ((yy * 16) + 80))
    scr_place_obj_map(114, ((xx * 16) + 136), ((yy * 16) + 63))
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 64), 0, obj_chest_cabinet)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 64), 0, obj_chest_cabinet)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 41), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 41), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 208), 0, obj_solid)
    var o_indoor = instance_create_depth(((xx * 16) + 128), ((yy * 16) + 192), 0, obj_indoor)
    o_indoor.tele_x = dest_x
    o_indoor.tele_y = dest_y
    var o_indoor2 = instance_create_depth((x + o.b_x[decor_id][image_index]), (y + o.b_y[decor_id][image_index]), 0, obj_indoor)
    o_indoor2.tele_x = (((xx * 16) + 8) + 128)
    o_indoor2.tele_y = (((yy * 16) + 5) + 192)
    tilemap_set(o.layer_tileset_floor_indoor, 334, (xx + 1), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 366, (xx + 1), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 1), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 1), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 1), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 1), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 1), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 1), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 334, (xx + 1), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 366, (xx + 1), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 2), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 2), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 2), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 2), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 367, (xx + 2), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 399, (xx + 2), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 399, (xx + 2), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 399, (xx + 2), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 399, (xx + 2), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 399, (xx + 2), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 3), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 3), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 3), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 3), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 368, (xx + 3), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 3), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 3), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 3), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 3), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 3), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 4), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 4), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 4), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 4), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 368, (xx + 4), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 4), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 4), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 4), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 4), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 4), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 5), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 5), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 5), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 5), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 368, (xx + 5), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 5), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 5), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 5), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 5), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 400, (xx + 5), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 6), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 6), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 6), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 6), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 369, (xx + 6), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 401, (xx + 6), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 401, (xx + 6), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 401, (xx + 6), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 401, (xx + 6), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 401, (xx + 6), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 7), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 7), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 7), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 7), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 7), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 7), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 7), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 7), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 7), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 7), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 8), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 8), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 8), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 8), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 8), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 8), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 8), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 8), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 8), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 371, (xx + 8), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 9), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 9), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 9), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 9), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 9), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 9), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 9), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 9), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 396, (xx + 9), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 428, (xx + 9), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 10), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 10), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 10), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 10), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 10), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 10), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 10), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 10), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 397, (xx + 10), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 429, (xx + 10), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 12))
    tilemap_set(o.layer_tileset_wall_below_indoor, 279, (xx + 1), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 1), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 247, (xx + 2), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 2), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 343, (xx + 3), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 375, (xx + 3), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 376, (xx + 3), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 247, (xx + 4), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 4), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 343, (xx + 5), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 375, (xx + 5), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 376, (xx + 5), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 247, (xx + 6), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 6), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 280, (xx + 7), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 7), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 120, (xx + 8), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 8), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 279, (xx + 9), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 9), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 343, (xx + 10), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 375, (xx + 10), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 376, (xx + 10), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 247, (xx + 11), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 11), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 280, (xx + 12), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 12), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 120, (xx + 13), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 152, (xx + 13), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 183, (xx + 0), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 57, (xx + 0), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 215, (xx + 0), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 0), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 0), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 1), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 1), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 1), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 1), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 2), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 2), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 2), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 2), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 3), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 3), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 3), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 3), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 4), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 4), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 4), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 4), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 5), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 5), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 5), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 5), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 6), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 6), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 6), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 6), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 7), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 25, (xx + 7), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 7), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 7), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 8), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 8), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 8), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 9), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 23, (xx + 9), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 9), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 9), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 10), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 10), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 10), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 10), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 11), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 11), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 11), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 11), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 12), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 12), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 12), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 12), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 88, (xx + 13), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 24, (xx + 13), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 13), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 13), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 184, (xx + 14), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 55, (xx + 14), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 216, (xx + 14), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 14), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 14), (yy + 14))
    return;
}

