my_id = 0
qnt = 0
ammo_adesso = 0
ammo_now_id = 0
durability = 100
livello_min = 1
created_from_player = 0
my_x = 0
my_y = 0
collision_with_item = 0
collision_with_same_item = 0
item_necessary = -1
caselle_x = 0
caselle_y = 0
offset_x = 0
offset_y = 0
rotation = 0
visto = 1
show_qnt = 0
alarm[1] = 2
lista_item()
prev_position = -1
position = -1
is_craftable = 1
alarm[0] = 1
alarm[5] = 2
alarm[3] = 3
list_item_necessary = ds_list_create()
list_item_necessary_scopo = ds_list_create()
item_necessary = 0
alarm[2] = 3
ammo_type = 0
mod_id[(0 << 0)] = -1
mod_id[(1 << 0)] = -1
mod_id[(3 << 0)] = -1
mod_id[(2 << 0)] = -1
mod_id[(5 << 0)] = -1
mod_id[(6 << 0)] = -1
mod_id[(4 << 0)] = -1
mod_id[(7 << 0)] = -1
mod_id[(8 << 0)] = -1
mod_id[(9 << 0)] = -1
mod_id[(10 << 0)] = -1
surface_item = surface_create(96, 32)
can_draw = 0
file_x = 0
file_y = 0
file_inv = 1
brake_x = 0
brake_y = 0
