function init_bt_ai_human() //gml_Script_init_bt_ai_human
{
    var i = 0
    tree_id[i] = (23 << 0)
    tree_parent[i] = 2
    tree_pos[i] = 0
    tree_child[i] = []
    i = 1
    tree_id[i] = (13 << 0)
    tree_parent[i] = 2
    tree_pos[i] = 1
    tree_child[i] = []
    i = 2
    tree_id[i] = (1 << 0)
    tree_parent[i] = 6
    tree_pos[i] = 2
    tree_child[i] = [1, 0]
    i = 3
    tree_id[i] = (21 << 0)
    tree_parent[i] = 6
    tree_pos[i] = 3
    tree_child[i] = []
    i = 4
    tree_id[i] = (4 << 0)
    tree_parent[i] = 6
    tree_pos[i] = 4
    tree_child[i] = [5]
    i = 5
    tree_id[i] = (12 << 0)
    tree_parent[i] = 4
    tree_pos[i] = 5
    tree_child[i] = []
    i = 6
    tree_id[i] = (2 << 0)
    tree_parent[i] = 9
    tree_pos[i] = 6
    tree_child[i] = [4, 2, 3]
    i = 7
    tree_id[i] = (4 << 0)
    tree_parent[i] = 8
    tree_pos[i] = 7
    tree_child[i] = [23]
    i = 8
    tree_id[i] = (2 << 0)
    tree_parent[i] = 21
    tree_pos[i] = 8
    tree_child[i] = [7, 22]
    i = 9
    tree_id[i] = (1 << 0)
    tree_parent[i] = 29
    tree_pos[i] = 9
    tree_child[i] = [11, 6]
    i = 10
    tree_id[i] = (4 << 0)
    tree_parent[i] = 25
    tree_pos[i] = 10
    tree_child[i] = [18]
    i = 11
    tree_id[i] = (2 << 0)
    tree_parent[i] = 9
    tree_pos[i] = 11
    tree_child[i] = [24, 21]
    i = 12
    tree_id[i] = (2 << 0)
    tree_parent[i] = 30
    tree_pos[i] = 12
    tree_child[i] = [29, 13]
    i = 13
    tree_id[i] = (18 << 0)
    tree_parent[i] = 12
    tree_pos[i] = 13
    tree_child[i] = []
    i = 14
    tree_id[i] = (25 << 0)
    tree_parent[i] = 29
    tree_pos[i] = 14
    tree_child[i] = []
    i = 15
    tree_id[i] = (24 << 0)
    tree_parent[i] = 17
    tree_pos[i] = 15
    tree_child[i] = []
    i = 16
    tree_id[i] = (15 << 0)
    tree_parent[i] = 17
    tree_pos[i] = 16
    tree_child[i] = []
    i = 17
    tree_id[i] = (2 << 0)
    tree_parent[i] = 29
    tree_pos[i] = 17
    tree_child[i] = [16, 15]
    i = 18
    tree_id[i] = (12 << 0)
    tree_parent[i] = 10
    tree_pos[i] = 18
    tree_child[i] = []
    i = 19
    tree_id[i] = (22 << 0)
    tree_parent[i] = 21
    tree_pos[i] = 19
    tree_child[i] = []
    i = 20
    tree_id[i] = (21 << 0)
    tree_parent[i] = 25
    tree_pos[i] = 20
    tree_child[i] = []
    i = 21
    tree_id[i] = (1 << 0)
    tree_parent[i] = 11
    tree_pos[i] = 21
    tree_child[i] = [25, 8, 19]
    i = 22
    tree_id[i] = (20 << 0)
    tree_parent[i] = 8
    tree_pos[i] = 22
    tree_child[i] = []
    i = 23
    tree_id[i] = (11 << 0)
    tree_parent[i] = 7
    tree_pos[i] = 23
    tree_child[i] = []
    i = 24
    tree_id[i] = (10 << 0)
    tree_parent[i] = 11
    tree_pos[i] = 24
    tree_child[i] = []
    i = 25
    tree_id[i] = (2 << 0)
    tree_parent[i] = 21
    tree_pos[i] = 25
    tree_child[i] = [10, 20]
    i = 26
    tree_id[i] = (9 << 0)
    tree_parent[i] = 28
    tree_pos[i] = 26
    tree_child[i] = []
    i = 27
    tree_id[i] = (8 << 0)
    tree_parent[i] = 28
    tree_pos[i] = 27
    tree_child[i] = []
    i = 28
    tree_id[i] = (1 << 0)
    tree_parent[i] = 29
    tree_pos[i] = 28
    tree_child[i] = [27, 26]
    i = 29
    tree_id[i] = (1 << 0)
    tree_parent[i] = 12
    tree_pos[i] = 29
    tree_child[i] = [28, 9, 9, 17, 14]
    i = 30
    tree_id[i] = (0 << 0)
    tree_parent[i] = -1
    tree_pos[i] = 30
    tree_child[i] = [12]
    var _size = array_length(tree_id)
    pos_roof = 0
    for (i = 0; i < _size; i++)
    {
        if (tree_parent[i] == -1)
            pos_roof = i
    }
    for (i = 0; i < _size; i++)
    {
        tree_node[i] = global.node_type[tree_id[i]]
        tree_node_child_now[i] = 0
        tree_condition_checked[i] = 9999
        tree_condition_checked_max[i] = global.node_check_condition_max[tree_id[i]]
        tree_condition_now[i] = 0
    }
    var _tree_size = array_length(tree_id)
    for (i = 0; i < _tree_size; i++)
    {
        var _t = ""
        var _node_id = tree_id[i]
        var _node_name = global.node_name[_node_id]
        _t += ("NAME : " + _node_name)
        var _parent = tree_parent[i]
        var _parent_name = ""
        if (_parent != -1)
            _parent_name = global.node_name[tree_id[_parent]]
        _t += (("  ;  PARENT: " + _parent_name) + "  ;  CHILD :")
        for (var j = 0; j < array_length(tree_child[i]); j++)
        {
            var _child_pos = tree_child[i][j]
            var _child_node_id = tree_id[_child_pos]
            var _name = global.node_name[_child_node_id]
            _t += (_name + " , ")
        }
        show_debug_message(_t)
    }
    return;
}

