open = 0
id_door = 0
var a = (0 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1665
global.door_sprite_open[a] = 1666
global.door_key_id[a] = (520 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (1 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1669
global.door_sprite_open[a] = 1670
global.door_key_id[a] = (521 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (2 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1669
global.door_sprite_open[a] = 1670
global.door_key_id[a] = (522 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (3 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1669
global.door_sprite_open[a] = 1670
global.door_key_id[a] = (530 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (4 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1669
global.door_sprite_open[a] = 1670
global.door_key_id[a] = (531 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (5 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1669
global.door_sprite_open[a] = 1670
global.door_key_id[a] = (532 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (6 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1665
global.door_sprite_open[a] = 1666
global.door_key_id[a] = (534 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (7 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1665
global.door_sprite_open[a] = 1666
global.door_key_id[a] = (538 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (8 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1669
global.door_sprite_open[a] = 1670
global.door_key_id[a] = (586 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (9 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1665
global.door_sprite_open[a] = 1666
global.door_key_id[a] = (587 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (10 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1665
global.door_sprite_open[a] = 1666
global.door_key_id[a] = (588 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (11 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1665
global.door_sprite_open[a] = 1666
global.door_key_id[a] = (590 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (13 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1665
global.door_sprite_open[a] = 1666
global.door_key_id[a] = (591 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
a = (12 << 0)
global.door_id[a] = a
global.door_sprite_close[a] = 1669
global.door_sprite_open[a] = 1670
global.door_key_id[a] = (589 << 0)
global.door_sound_close[a] = 0
global.door_sound_open[a] = 0
