if file_exists("all_loot.ini")
    file_delete("all_loot.ini")
if ds_exists(global.grid_move, 5)
    ds_grid_destroy(global.grid_move)
if ds_exists(grid_motion, 5)
    ds_grid_destroy(grid_motion)
if ds_exists(grid_quest, 5)
    ds_grid_destroy(grid_quest)
if ds_exists(global.craft_grid, 5)
    ds_grid_destroy(global.craft_grid)
if ds_exists(global.grid_craft_i, 5)
    ds_grid_destroy(global.grid_craft_i)
if ds_exists(global.grid_check_n_item_requiered, 5)
    ds_grid_destroy(global.grid_check_n_item_requiered)
if ds_exists(global.grid_faction, 5)
    ds_grid_destroy(global.grid_faction)
if ds_exists(global.list_status_id, 2)
    ds_list_destroy(global.list_status_id)
if ds_exists(global.list_quest_before_map_npc_name, 2)
    ds_list_destroy(global.list_quest_before_map_npc_name)
if ds_exists(global.list_quest_before_map_quest_id, 2)
    ds_list_destroy(global.list_quest_before_map_quest_id)
if ds_exists(global.list_quest_before_map_quest_premio, 2)
    ds_list_destroy(global.list_quest_before_map_quest_premio)
