global.type_node_name[(0 << 0)] = "type_node.roof"
global.type_node_name[(1 << 0)] = "type_node.sequence"
global.type_node_name[(2 << 0)] = "type_node.fallback"
global.type_node_name[(3 << 0)] = "type_node.condition"
global.type_node_name[(4 << 0)] = "type_node.action"
global.type_node_name[(5 << 0)] = "type_node.invert"
for (var i = 0; i < (27 << 0); i++)
    global.node_check_condition_max[i] = 0
var a = (0 << 0)
global.node_name[a] = "bt.roof "
global.node_id[a] = a
global.node_type[a] = (0 << 0)
a = (2 << 0)
global.node_name[a] = "bt.fallback"
global.node_id[a] = a
global.node_type[a] = (2 << 0)
a = (1 << 0)
global.node_name[a] = "bt.sequence"
global.node_id[a] = a
global.node_type[a] = (1 << 0)
a = (4 << 0)
global.node_name[a] = "bt.invert"
global.node_id[a] = a
global.node_type[a] = (5 << 0)
a = (5 << 0)
global.node_name[a] = "bt.target_near"
global.node_id[a] = a
global.node_type[a] = (3 << 0)
a = (7 << 0)
global.node_name[a] = "bt.pos_raggiunta"
global.node_id[a] = a
global.node_type[a] = (3 << 0)
a = (8 << 0)
global.node_name[a] = "bt.target_found"
global.node_id[a] = a
global.node_type[a] = (3 << 0)
a = (9 << 0)
global.node_name[a] = "bt.target_is_enemy"
global.node_id[a] = a
global.node_type[a] = (3 << 0)
a = (10 << 0)
global.node_name[a] = "bt.target_in_sight"
global.node_id[a] = a
global.node_type[a] = (3 << 0)
a = (11 << 0)
global.node_name[a] = "bt.target_last_seen_is_near"
global.node_id[a] = a
global.node_type[a] = (3 << 0)
a = (14 << 0)
global.node_name[a] = "bt.pos_cover_near"
global.node_id[a] = a
global.node_type[a] = (3 << 0)
a = (12 << 0)
global.node_name[a] = "bt.need_reload"
global.node_id[a] = a
global.node_type[a] = (3 << 0)
a = (16 << 0)
global.node_name[a] = "bt.sto_ricaricando"
global.node_id[a] = a
global.node_type[a] = (3 << 0)
a = (13 << 0)
global.node_name[a] = "bt.pos_cover_found"
global.node_id[a] = a
global.node_type[a] = (3 << 0)
a = (15 << 0)
global.node_name[a] = "bt.weapon_dir_towards_target"
global.node_id[a] = a
global.node_type[a] = (3 << 0)
a = (17 << 0)
global.node_name[a] = "bt.move_to_target"
global.node_id[a] = a
global.node_type[a] = (4 << 0)
a = (19 << 0)
global.node_name[a] = "bt.move_to_start_pos"
global.node_id[a] = a
global.node_type[a] = (4 << 0)
a = (18 << 0)
global.node_name[a] = "bt.idle"
global.node_id[a] = a
global.node_type[a] = (4 << 0)
a = (20 << 0)
global.node_name[a] = "bt.searching_target"
global.node_id[a] = a
global.node_type[a] = (4 << 0)
a = (21 << 0)
global.node_name[a] = "bt.reload"
global.node_id[a] = a
global.node_type[a] = (4 << 0)
a = (22 << 0)
global.node_name[a] = "bt.chase"
global.node_id[a] = a
global.node_type[a] = (4 << 0)
a = (23 << 0)
global.node_name[a] = "bt.cover"
global.node_id[a] = a
global.node_type[a] = (4 << 0)
a = (24 << 0)
global.node_name[a] = "bt.rotate_weapon"
global.node_id[a] = a
global.node_type[a] = (4 << 0)
a = (25 << 0)
global.node_name[a] = "bt.shoot"
global.node_id[a] = a
global.node_type[a] = (4 << 0)
a = (26 << 0)
global.node_name[a] = "bt.idle_no_move"
global.node_id[a] = a
global.node_type[a] = (4 << 0)
