function scr_b_lair_ghoul(argument0, argument1) //gml_Script_scr_b_lair_ghoul
{
    var xx = argument0
    var yy = argument1
    scr_place_obj_map(2, ((xx * 16) + 126), ((yy * 16) + 85))
    scr_place_obj_map(2, ((xx * 16) + 94), ((yy * 16) + 114))
    scr_place_obj_map(2, ((xx * 16) + 50), ((yy * 16) + 115))
    scr_place_obj_map(2, ((xx * 16) + 103), ((yy * 16) + 129))
    scr_place_obj_map(2, ((xx * 16) + 37), ((yy * 16) + 130))
    scr_place_obj_map(2, ((xx * 16) + 87), ((yy * 16) + 57))
    scr_place_obj_map(2, ((xx * 16) + 72), ((yy * 16) + 64))
    scr_place_obj_map(2, ((xx * 16) + 80), ((yy * 16) + 48))
    scr_place_obj_map(2, ((xx * 16) + 64), ((yy * 16) + 48))
    scr_place_obj_map(2, ((xx * 16) + 97), ((yy * 16) + 74))
    scr_place_obj_map(2, ((xx * 16) + 105), ((yy * 16) + 94))
    scr_place_obj_map(2, ((xx * 16) + 113), ((yy * 16) + 62))
    scr_place_obj_map(2, ((xx * 16) + 53), ((yy * 16) + 64))
    scr_place_obj_map(2, ((xx * 16) + 41), ((yy * 16) + 85))
    scr_place_obj_map(2, ((xx * 16) + 32), ((yy * 16) + 96))
    scr_place_obj_map(201, ((xx * 16) + 48), ((yy * 16) + 96))
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 128), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 128), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 48), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 32), 0, obj_enemy_ghoul)
    ds_grid_set(grid_floor2, (xx + 0), (yy + 3), 0)
    ds_grid_set(grid_floor2, (xx + 0), (yy + 4), 0)
    ds_grid_set(grid_floor2, (xx + 0), (yy + 5), 0)
    ds_grid_set(grid_floor2, (xx + 1), (yy + 2), 0)
    ds_grid_set(grid_floor2, (xx + 1), (yy + 3), 0)
    ds_grid_set(grid_floor2, (xx + 1), (yy + 4), 0)
    ds_grid_set(grid_floor2, (xx + 1), (yy + 5), 0)
    ds_grid_set(grid_floor2, (xx + 1), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 1), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 2), (yy + 1), 0)
    ds_grid_set(grid_floor2, (xx + 2), (yy + 2), 0)
    ds_grid_set(grid_floor2, (xx + 2), (yy + 3), 0)
    ds_grid_set(grid_floor2, (xx + 2), (yy + 4), 0)
    ds_grid_set(grid_floor2, (xx + 2), (yy + 5), 0)
    ds_grid_set(grid_floor2, (xx + 2), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 2), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 2), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 0), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 1), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 2), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 3), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 4), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 5), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 9), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 0), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 1), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 2), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 3), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 4), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 9), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 0), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 1), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 2), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 3), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 4), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 5), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 9), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 1), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 2), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 3), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 4), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 5), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 7), (yy + 2), 0)
    ds_grid_set(grid_floor2, (xx + 7), (yy + 3), 0)
    ds_grid_set(grid_floor2, (xx + 7), (yy + 4), 0)
    ds_grid_set(grid_floor2, (xx + 7), (yy + 5), 0)
    ds_grid_set(grid_floor2, (xx + 7), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 7), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 8), (yy + 3), 0)
    ds_grid_set(grid_floor2, (xx + 8), (yy + 4), 0)
    ds_grid_set(grid_floor2, (xx + 8), (yy + 5), 0)
    ds_grid_set(grid_floor2, (xx + 8), (yy + 6), 0)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 96), 0, obj_quest_approach_lair_2)
    return;
}

