lista_item()
prev_mouse_x = 0
prev_mouse_y = 0
show_item_stat = 0
show_item_stat_step = 0
show_item_stat_max = 25
show_item_instance_id = -4
instance_id_temp = -4
instance_id_prev = -4
off_n_v = 52
global.show_overlay_col_min = 65280
global.show_overlay_col_max = 255
global.show_overlay_col[0] = 65280
global.show_overlay_col[1] = 60927
global.show_overlay_col[2] = 34815
global.show_overlay_col[3] = 17663
global.show_overlay_col[4] = 255
global.show_overlay_col_number = array_length_1d(global.show_overlay_col)
global.show_overlay_peso_min = 0
global.show_overlay_peso_max = 2.5
global.show_overlay_soldi_min = 0
global.show_overlay_soldi_max = 10000
global.show_overlay_peso_x = 41
global.show_overlay_peso_y = 242
global.show_overlay_peso_w = 78
global.show_overlay_peso_h = 13
global.show_overlay_soldi_x = ((global.show_overlay_peso_x + global.show_overlay_peso_w) + 1)
global.show_overlay_soldi_y = global.show_overlay_peso_y
global.show_overlay_soldi_w = 50
global.show_overlay_soldi_h = global.show_overlay_peso_h

global.show_overlay_price_kg_x = 200
global.show_overlay_price_kg_y = 240
global.show_overlay_price_kg_w = 100
global.show_overlay_price_kg_h = 10
global.show_overlay_price_slot_x = global.show_overlay_price_kg_x
global.show_overlay_price_slot_y = (global.show_overlay_price_kg_y + global.show_overlay_price_kg_h)
global.show_overlay_price_slot_w = global.show_overlay_price_kg_w
global.show_overlay_price_slot_h = global.show_overlay_price_kg_h
