function scr_indoor_house_wood_5(argument0, argument1, argument2, argument3) //gml_Script_scr_indoor_house_wood_5
{
    var xx = argument0
    var yy = argument1
    var dest_x = argument2
    var dest_y = argument3
    var o = obj_map_generator
    scr_place_obj_map(104, ((xx * 16) + 31), ((yy * 16) + 71))
    scr_place_obj_map(104, ((xx * 16) + 85), ((yy * 16) + 62))
    scr_place_obj_map(104, ((xx * 16) + 59), ((yy * 16) + 56))
    scr_place_obj_map(104, ((xx * 16) + 47), ((yy * 16) + 70))
    scr_place_obj_map(62, ((xx * 16) + 64), ((yy * 16) + 51))
    scr_place_obj_map(62, ((xx * 16) + 40), ((yy * 16) + 51))
    scr_place_obj_map(62, ((xx * 16) + 67), ((yy * 16) + 41))
    scr_place_obj_map(62, ((xx * 16) + 55), ((yy * 16) + 44))
    scr_place_obj_map(62, ((xx * 16) + 42), ((yy * 16) + 41))
    scr_place_obj_map(105, ((xx * 16) + 98), ((yy * 16) + 55))
    scr_place_obj_map(105, ((xx * 16) + 103), ((yy * 16) + 82))
    scr_place_obj_map(105, ((xx * 16) + 96), ((yy * 16) + 112))
    scr_place_obj_map(105, ((xx * 16) + 31), ((yy * 16) + 55))
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 80), 0, obj_chest_tool_box)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 112), 0, obj_solid)
    var o_indoor = instance_create_depth(((xx * 16) + 48), ((yy * 16) + 96), 0, obj_indoor)
    o_indoor.tele_x = dest_x
    o_indoor.tele_y = dest_y
    var o_indoor2 = instance_create_depth((x + o.b_x[decor_id][image_index]), (y + o.b_y[decor_id][image_index]), 0, obj_indoor)
    o_indoor2.tele_x = (((xx * 16) + 8) + 48)
    o_indoor2.tele_y = (((yy * 16) + 5) + 96)
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 0), (yy + 0))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 0), (yy + 1))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 0), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 0), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 0), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 0), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 0), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 1), (yy + 0))
    tilemap_set(o.layer_tileset_floor_indoor, 384, (xx + 1), (yy + 1))
    tilemap_set(o.layer_tileset_floor_indoor, 416, (xx + 1), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 384, (xx + 1), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 416, (xx + 1), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 384, (xx + 1), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 416, (xx + 1), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 2), (yy + 0))
    tilemap_set(o.layer_tileset_floor_indoor, 385, (xx + 2), (yy + 1))
    tilemap_set(o.layer_tileset_floor_indoor, 417, (xx + 2), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 385, (xx + 2), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 417, (xx + 2), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 385, (xx + 2), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 417, (xx + 2), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 3), (yy + 0))
    tilemap_set(o.layer_tileset_floor_indoor, 384, (xx + 3), (yy + 1))
    tilemap_set(o.layer_tileset_floor_indoor, 416, (xx + 3), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 384, (xx + 3), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 416, (xx + 3), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 384, (xx + 3), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 416, (xx + 3), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 4), (yy + 0))
    tilemap_set(o.layer_tileset_floor_indoor, 385, (xx + 4), (yy + 1))
    tilemap_set(o.layer_tileset_floor_indoor, 417, (xx + 4), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 385, (xx + 4), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 417, (xx + 4), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 385, (xx + 4), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 417, (xx + 4), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 5), (yy + 0))
    tilemap_set(o.layer_tileset_floor_indoor, 384, (xx + 5), (yy + 1))
    tilemap_set(o.layer_tileset_floor_indoor, 416, (xx + 5), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 384, (xx + 5), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 416, (xx + 5), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 384, (xx + 5), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 416, (xx + 5), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 6), (yy + 0))
    tilemap_set(o.layer_tileset_floor_indoor, 385, (xx + 6), (yy + 1))
    tilemap_set(o.layer_tileset_floor_indoor, 417, (xx + 6), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 385, (xx + 6), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 417, (xx + 6), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 385, (xx + 6), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 417, (xx + 6), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 7), (yy + 0))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 7), (yy + 1))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 7), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 7), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 7), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 7), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 32, (xx + 7), (yy + 6))
    tilemap_set(o.layer_tileset_wall_below_indoor, 98, (xx + 1), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 99, (xx + 2), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 98, (xx + 3), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 99, (xx + 4), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 98, (xx + 5), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 99, (xx + 6), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 161, (xx + 0), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 36, (xx + 0), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 36, (xx + 0), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 36, (xx + 0), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 36, (xx + 0), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 36, (xx + 0), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 193, (xx + 0), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 0), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 66, (xx + 1), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 2, (xx + 1), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 1), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 67, (xx + 2), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 2, (xx + 2), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 2), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 66, (xx + 3), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 2, (xx + 3), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 3), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 67, (xx + 4), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 2, (xx + 4), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 4), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 66, (xx + 5), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 2, (xx + 5), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 5), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 67, (xx + 6), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 2, (xx + 6), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 6), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 162, (xx + 7), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 33, (xx + 7), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 33, (xx + 7), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 33, (xx + 7), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 33, (xx + 7), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 33, (xx + 7), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 194, (xx + 7), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 32, (xx + 7), (yy + 7))
    return;
}

