function scr_indoor_warehouse_2(argument0, argument1, argument2, argument3) //gml_Script_scr_indoor_warehouse_2
{
    var xx = argument0
    var yy = argument1
    var dest_x = argument2
    var dest_y = argument3
    var o = obj_map_generator
    scr_place_obj_map(123, ((xx * 16) + 23), ((yy * 16) + 190))
    scr_place_obj_map(123, ((xx * 16) + 256), ((yy * 16) + 112))
    scr_place_obj_map(123, ((xx * 16) + 96), ((yy * 16) + 112))
    scr_place_obj_map(123, ((xx * 16) + 32), ((yy * 16) + 400))
    scr_place_obj_map(123, ((xx * 16) + 208), ((yy * 16) + 416))
    scr_place_obj_map(123, ((xx * 16) + 96), ((yy * 16) + 320))
    scr_place_obj_map(123, ((xx * 16) + 288), ((yy * 16) + 240))
    scr_place_obj_map(123, ((xx * 16) + 68), ((yy * 16) + 234))
    scr_place_obj_map(82, ((xx * 16) + 288), ((yy * 16) + 160))
    scr_place_obj_map(111, ((xx * 16) + 120), ((yy * 16) + 115))
    scr_place_obj_map(111, ((xx * 16) + 147), ((yy * 16) + 134))
    scr_place_obj_map(111, ((xx * 16) + 118), ((yy * 16) + 155))
    scr_place_obj_map(106, ((xx * 16) + 128), ((yy * 16) + 144))
    scr_place_obj_map(114, ((xx * 16) + 216), ((yy * 16) + 80))
    scr_place_obj_map(114, ((xx * 16) + 184), ((yy * 16) + 80))
    scr_place_obj_map(114, ((xx * 16) + 168), ((yy * 16) + 80))
    scr_place_obj_map(113, ((xx * 16) + 256), ((yy * 16) + 80))
    scr_place_obj_map(101, ((xx * 16) + 33), ((yy * 16) + 102))
    scr_place_obj_map(101, ((xx * 16) + 51), ((yy * 16) + 104))
    scr_place_obj_map(101, ((xx * 16) + 80), ((yy * 16) + 100))
    scr_place_obj_map(101, ((xx * 16) + 43), ((yy * 16) + 129))
    scr_place_obj_map(101, ((xx * 16) + 50), ((yy * 16) + 142))
    scr_place_obj_map(101, ((xx * 16) + 68), ((yy * 16) + 105))
    scr_place_obj_map(101, ((xx * 16) + 53), ((yy * 16) + 117))
    scr_place_obj_map(101, ((xx * 16) + 37), ((yy * 16) + 115))
    scr_place_obj_map(101, ((xx * 16) + 26), ((yy * 16) + 133))
    scr_place_obj_map(101, ((xx * 16) + 26), ((yy * 16) + 117))
    scr_place_obj_map(101, ((xx * 16) + 18), ((yy * 16) + 104))
    scr_place_obj_map(156, ((xx * 16) + 272), ((yy * 16) + 144))
    scr_place_obj_map(156, ((xx * 16) + 272), ((yy * 16) + 128))
    scr_place_obj_map(156, ((xx * 16) + 272), ((yy * 16) + 112))
    scr_place_obj_map(105, ((xx * 16) + 121), ((yy * 16) + 88))
    scr_place_obj_map(105, ((xx * 16) + 98), ((yy * 16) + 91))
    scr_place_obj_map(105, ((xx * 16) + 75), ((yy * 16) + 88))
    scr_place_obj_map(105, ((xx * 16) + 51), ((yy * 16) + 90))
    scr_place_obj_map(105, ((xx * 16) + 294), ((yy * 16) + 87))
    scr_place_obj_map(105, ((xx * 16) + 32), ((yy * 16) + 160))
    scr_place_obj_map(105, ((xx * 16) + 27), ((yy * 16) + 86))
    scr_place_obj_map(171, ((xx * 16) + 240), ((yy * 16) + 256))
    scr_place_obj_map(171, ((xx * 16) + 240), ((yy * 16) + 208))
    scr_place_obj_map(171, ((xx * 16) + 208), ((yy * 16) + 208))
    scr_place_obj_map(171, ((xx * 16) + 208), ((yy * 16) + 256))
    scr_place_obj_map(171, ((xx * 16) + 240), ((yy * 16) + 304))
    scr_place_obj_map(171, ((xx * 16) + 208), ((yy * 16) + 304))
    scr_place_obj_map(171, ((xx * 16) + 240), ((yy * 16) + 352))
    scr_place_obj_map(171, ((xx * 16) + 208), ((yy * 16) + 400))
    scr_place_obj_map(171, ((xx * 16) + 208), ((yy * 16) + 352))
    scr_place_obj_map(171, ((xx * 16) + 240), ((yy * 16) + 400))
    scr_place_obj_map(171, ((xx * 16) + 176), ((yy * 16) + 400))
    scr_place_obj_map(171, ((xx * 16) + 176), ((yy * 16) + 352))
    scr_place_obj_map(171, ((xx * 16) + 176), ((yy * 16) + 304))
    scr_place_obj_map(171, ((xx * 16) + 176), ((yy * 16) + 256))
    scr_place_obj_map(171, ((xx * 16) + 176), ((yy * 16) + 208))
    scr_place_obj_map(171, ((xx * 16) + 112), ((yy * 16) + 256))
    scr_place_obj_map(171, ((xx * 16) + 112), ((yy * 16) + 208))
    scr_place_obj_map(171, ((xx * 16) + 80), ((yy * 16) + 208))
    scr_place_obj_map(171, ((xx * 16) + 112), ((yy * 16) + 304))
    scr_place_obj_map(171, ((xx * 16) + 80), ((yy * 16) + 256))
    scr_place_obj_map(171, ((xx * 16) + 80), ((yy * 16) + 304))
    scr_place_obj_map(171, ((xx * 16) + 112), ((yy * 16) + 352))
    scr_place_obj_map(171, ((xx * 16) + 80), ((yy * 16) + 400))
    scr_place_obj_map(171, ((xx * 16) + 80), ((yy * 16) + 352))
    scr_place_obj_map(171, ((xx * 16) + 112), ((yy * 16) + 400))
    scr_place_obj_map(171, ((xx * 16) + 112), ((yy * 16) + 448))
    scr_place_obj_map(171, ((xx * 16) + 80), ((yy * 16) + 448))
    scr_place_obj_map(171, ((xx * 16) + 16), ((yy * 16) + 448))
    scr_place_obj_map(171, ((xx * 16) + 48), ((yy * 16) + 448))
    scr_place_obj_map(171, ((xx * 16) + 48), ((yy * 16) + 400))
    scr_place_obj_map(171, ((xx * 16) + 48), ((yy * 16) + 352))
    scr_place_obj_map(171, ((xx * 16) + 48), ((yy * 16) + 304))
    scr_place_obj_map(171, ((xx * 16) + 48), ((yy * 16) + 256))
    scr_place_obj_map(171, ((xx * 16) + 48), ((yy * 16) + 208))
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 96), 0, obj_enemy_rat)
    instance_create_depth(((xx * 16) + 240), ((yy * 16) + 144), 0, obj_enemy_rat)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 160), 0, obj_enemy_rat)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 320), 0, obj_enemy_rat)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 272), 0, obj_enemy_rat)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 224), 0, obj_enemy_rat)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 128), 0, obj_enemy_rat)
    instance_create_depth(((xx * 16) + 94), ((yy * 16) + 219), 0, obj_chest_electronic_box)
    instance_create_depth(((xx * 16) + 52), ((yy * 16) + 152), 0, obj_chest_medication_box)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 80), 0, obj_chest_cabinet)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 80), 0, obj_chest_cabinet)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 80), 0, obj_chest_cabinet)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 432), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 416), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 400), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 384), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 368), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 352), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 336), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 240), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 240), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 288), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 240), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 336), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 352), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 368), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 384), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 400), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 416), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 432), 0, obj_solid)
    instance_create_depth(((xx * 16) + 288), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 240), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 448), 0, obj_solid)
    var o_indoor = instance_create_depth(((xx * 16) + 256), ((yy * 16) + 432), 0, obj_indoor)
    o_indoor.tele_x = dest_x
    o_indoor.tele_y = dest_y
    var o_indoor2 = instance_create_depth((x + o.b_x[decor_id][image_index]), (y + o.b_y[decor_id][image_index]), 0, obj_indoor)
    o_indoor2.tele_x = (((xx * 16) + 8) + 256)
    o_indoor2.tele_y = (((yy * 16) + 5) + 432)
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 1), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 1), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 1), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 1), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 1), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 1), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 1), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 1), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 2), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 2), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 2), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 2), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 2), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 2), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 2), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 2), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 3), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 3), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 3), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 3), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 3), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 3), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 3), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 3), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 4), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 4), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 4), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 4), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 4), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 4), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 4), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 4), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 5), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 5), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 5), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 5), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 5), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 5), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 5), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 5), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 6), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 6), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 6), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 6), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 6), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 6), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 6), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 6), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 7), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 7), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 7), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 7), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 7), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 7), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 7), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 7), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 8), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 8), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 8), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 8), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 8), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 8), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 8), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 8), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 9), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 9), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 9), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 9), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 9), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 9), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 9), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 9), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 10), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 10), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 10), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 10), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 10), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 10), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 10), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 10), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 11), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 11), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 11), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 12), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 12), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 12), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 13), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 13), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 13), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 13), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 13), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 13), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 13), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 13), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 14), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 14), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 14), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 14), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 14), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 14), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 14), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 14), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 15), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 15), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 15), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 15), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 15), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 15), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 15), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 15), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 16), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 16), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 16), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 16), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 16), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 16), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 16), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 16), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 17), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 17), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 17), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 17), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 17), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 17), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 17), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 17), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 18), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 18), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 18), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 18), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 18), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 425, (xx + 18), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 336, (xx + 18), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 293, (xx + 18), (yy + 27))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 1), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 1), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 334, (xx + 1), (yy + 10))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 2), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 2), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 499, (xx + 2), (yy + 15))
    tilemap_set(o.layer_tileset_wall_below_indoor, 492, (xx + 2), (yy + 20))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 3), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 3), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 4), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 4), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 494, (xx + 4), (yy + 7))
    tilemap_set(o.layer_tileset_wall_below_indoor, 460, (xx + 4), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 5), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 5), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 492, (xx + 5), (yy + 25))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 6), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 6), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 7), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 7), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 457, (xx + 7), (yy + 5))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 8), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 8), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 494, (xx + 8), (yy + 6))
    tilemap_set(o.layer_tileset_wall_below_indoor, 494, (xx + 8), (yy + 14))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 9), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 9), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 10), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 10), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 494, (xx + 10), (yy + 20))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 11), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 11), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 12), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 12), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 492, (xx + 12), (yy + 6))
    tilemap_set(o.layer_tileset_wall_below_indoor, 492, (xx + 12), (yy + 14))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 13), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 13), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 457, (xx + 13), (yy + 7))
    tilemap_set(o.layer_tileset_wall_below_indoor, 494, (xx + 13), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 14), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 14), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 467, (xx + 14), (yy + 5))
    tilemap_set(o.layer_tileset_wall_below_indoor, 496, (xx + 14), (yy + 19))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 15), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 15), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 460, (xx + 15), (yy + 6))
    tilemap_set(o.layer_tileset_wall_below_indoor, 462, (xx + 15), (yy + 14))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 16), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 16), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 494, (xx + 16), (yy + 25))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 17), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 17), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 500, (xx + 17), (yy + 20))
    tilemap_set(o.layer_tileset_wall_below_indoor, 545, (xx + 18), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 577, (xx + 18), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 489, (xx + 18), (yy + 11))
    tilemap_set(o.layer_tileset_wall_below_indoor, 467, (xx + 18), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 608, (xx + 0), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 15))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 20))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 21))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 22))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 23))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 24))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 25))
    tilemap_set(o.layer_tileset_wall_above_indoor, 482, (xx + 0), (yy + 26))
    tilemap_set(o.layer_tileset_wall_above_indoor, 640, (xx + 0), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 0), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 0), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 1), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 1), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 1), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 1), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 2), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 2), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 2), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 2), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 3), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 3), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 3), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 3), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 4), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 4), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 4), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 4), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 5), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 5), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 5), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 5), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 6), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 6), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 6), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 6), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 7), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 7), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 7), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 7), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 8), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 8), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 8), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 8), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 9), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 9), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 9), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 9), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 10), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 10), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 10), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 10), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 11), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 11), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 11), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 11), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 12), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 12), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 12), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 12), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 13), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 13), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 13), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 13), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 14), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 14), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 14), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 14), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 15), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 15), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 15), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 15), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 16), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 16), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 16), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 16), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 17), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 17), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 17), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 17), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 513, (xx + 18), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 449, (xx + 18), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 18), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 18), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 609, (xx + 19), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 15))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 20))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 21))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 22))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 23))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 24))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 25))
    tilemap_set(o.layer_tileset_wall_above_indoor, 480, (xx + 19), (yy + 26))
    tilemap_set(o.layer_tileset_wall_above_indoor, 641, (xx + 19), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 19), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 481, (xx + 19), (yy + 29))
    return;
}

