function scr_indoor_lair_ghoul_1(argument0, argument1, argument2, argument3) //gml_Script_scr_indoor_lair_ghoul_1
{
    var xx = argument0
    var yy = argument1
    var dest_x = argument2
    var dest_y = argument3
    var o = obj_map_generator
    scr_place_obj_map(282, ((xx * 16) + 33), ((yy * 16) + 94))
    scr_place_obj_map(282, ((xx * 16) + 24), ((yy * 16) + 94))
    scr_place_obj_map(282, ((xx * 16) + 38), ((yy * 16) + 86))
    scr_place_obj_map(282, ((xx * 16) + 29), ((yy * 16) + 86))
    scr_place_obj_map(282, ((xx * 16) + 20), ((yy * 16) + 86))
    scr_place_obj_map(282, ((xx * 16) + 20), ((yy * 16) + 78))
    scr_place_obj_map(282, ((xx * 16) + 38), ((yy * 16) + 78))
    scr_place_obj_map(282, ((xx * 16) + 29), ((yy * 16) + 78))
    scr_place_obj_map(282, ((xx * 16) + 33), ((yy * 16) + 70))
    scr_place_obj_map(282, ((xx * 16) + 24), ((yy * 16) + 70))
    instance_create_depth(((xx * 16) + 367), ((yy * 16) + 80), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 259), ((yy * 16) + 183), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 441), ((yy * 16) + 346), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 416), ((yy * 16) + 64), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 64), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 96), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 176), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 224), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 416), ((yy * 16) + 192), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 416), ((yy * 16) + 432), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 304), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 304), 0, obj_enemy_ghoul)
    instance_create_depth(((xx * 16) + 336), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 336), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 336), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 336), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 320), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 288), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 288), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 320), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 336), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 336), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 352), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 368), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 384), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 400), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 400), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 400), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 384), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 368), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 368), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 368), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 368), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 368), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 352), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 336), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 240), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 240), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 240), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 288), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 320), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 336), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 352), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 352), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 368), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 384), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 384), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 384), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 384), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 320), ((yy * 16) + 336), 0, obj_solid)
    instance_create_depth(((xx * 16) + 320), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 288), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 240), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 336), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 352), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 352), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 352), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 336), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 240), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 240), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 240), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 432), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 432), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 416), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 416), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 416), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 416), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 416), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 416), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 416), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 400), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 400), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 384), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 384), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 368), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 368), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 352), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 352), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 352), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 336), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 240), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 240), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 288), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 320), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 336), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 352), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 368), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 384), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 400), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 416), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 432), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 448), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 448), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 448), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 448), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 448), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 240), 0, obj_solid)
    instance_create_depth(((xx * 16) + 448), ((yy * 16) + 240), 0, obj_solid)
    instance_create_depth(((xx * 16) + 448), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 432), ((yy * 16) + 256), 0, obj_solid)
    instance_create_depth(((xx * 16) + 432), ((yy * 16) + 272), 0, obj_solid)
    instance_create_depth(((xx * 16) + 432), ((yy * 16) + 288), 0, obj_solid)
    instance_create_depth(((xx * 16) + 320), ((yy * 16) + 352), 0, obj_solid)
    instance_create_depth(((xx * 16) + 336), ((yy * 16) + 352), 0, obj_solid)
    instance_create_depth(((xx * 16) + 352), ((yy * 16) + 352), 0, obj_solid)
    instance_create_depth(((xx * 16) + 352), ((yy * 16) + 352), 0, obj_solid)
    instance_create_depth(((xx * 16) + 352), ((yy * 16) + 336), 0, obj_solid)
    instance_create_depth(((xx * 16) + 368), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 368), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 384), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 432), ((yy * 16) + 304), 0, obj_solid)
    instance_create_depth(((xx * 16) + 448), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 320), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 336), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 352), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 368), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 384), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 400), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 416), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 432), 0, obj_solid)
    instance_create_depth(((xx * 16) + 464), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 448), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 448), ((yy * 16) + 464), 0, obj_solid)
    instance_create_depth(((xx * 16) + 432), ((yy * 16) + 464), 0, obj_solid)
    instance_create_depth(((xx * 16) + 416), ((yy * 16) + 464), 0, obj_solid)
    instance_create_depth(((xx * 16) + 400), ((yy * 16) + 464), 0, obj_solid)
    instance_create_depth(((xx * 16) + 384), ((yy * 16) + 464), 0, obj_solid)
    instance_create_depth(((xx * 16) + 368), ((yy * 16) + 464), 0, obj_solid)
    instance_create_depth(((xx * 16) + 368), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 352), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 352), ((yy * 16) + 432), 0, obj_solid)
    instance_create_depth(((xx * 16) + 352), ((yy * 16) + 416), 0, obj_solid)
    instance_create_depth(((xx * 16) + 352), ((yy * 16) + 400), 0, obj_solid)
    instance_create_depth(((xx * 16) + 336), ((yy * 16) + 400), 0, obj_solid)
    instance_create_depth(((xx * 16) + 320), ((yy * 16) + 400), 0, obj_solid)
    instance_create_depth(((xx * 16) + 320), ((yy * 16) + 416), 0, obj_solid)
    instance_create_depth(((xx * 16) + 320), ((yy * 16) + 432), 0, obj_solid)
    instance_create_depth(((xx * 16) + 304), ((yy * 16) + 432), 0, obj_solid)
    instance_create_depth(((xx * 16) + 288), ((yy * 16) + 432), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 432), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 432), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 448), 0, obj_solid)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 464), 0, obj_solid)
    instance_create_depth(((xx * 16) + 256), ((yy * 16) + 464), 0, obj_solid)
    instance_create_depth(((xx * 16) + 240), ((yy * 16) + 464), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 464), 0, obj_solid)
    var o_indoor = instance_create_depth(((xx * 16) + 248), ((yy * 16) + 442), 0, obj_indoor)
    o_indoor.tele_x = dest_x
    o_indoor.tele_y = dest_y
    var o_indoor2 = instance_create_depth((x + o.b_x[decor_id][image_index]), (y + o.b_y[decor_id][image_index]), 0, obj_indoor)
    o_indoor2.tele_x = (((xx * 16) + 8) + 248)
    o_indoor2.tele_y = (((yy * 16) + 5) + 442)
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 1), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 1), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 1), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 1), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 1), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 2), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 2), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 2), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 2), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 2), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 2), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 2), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 2), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 2), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 2), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 2), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 2), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 3), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 3), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 3), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 3), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 4), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 5), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 5), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 6), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 6), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 6), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 6), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 7), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 7), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 7), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 7), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 8), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 8), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 8), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 9), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 10), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 10), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 10), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 10), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 10), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 10), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 10), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 10), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 10), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 10), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 10), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 10), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 11), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 11), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 11), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 11), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 11), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 11), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 11), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 11), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 11), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 11), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 12), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 12), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 12), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 12), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 12), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 12), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 12), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 12), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 12), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 13), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 13), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 13), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 13), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 13), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 13), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 13), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 13), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 13), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 13), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 13), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 13), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 14), (yy + 28))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 15), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 15), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 15), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 15), (yy + 28))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 16), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 16), (yy + 28))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 17), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 17), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 17), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 18), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 18), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 18), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 18), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 19), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 19), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 20), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 20), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 20), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 20), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 20), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 20), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 20), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 20), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 20), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 20), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 20), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 20), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 20), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 21), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 21), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 21), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 21), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 21), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 21), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 21), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 21), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 21), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 21), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 21), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 22), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 22), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 22), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 22), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 22), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 22), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 22), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 22), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 22), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 22), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 22), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 23), (yy + 28))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 24), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 28))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 24), (yy + 29))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 25), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 25), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 25), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 25), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 25), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 28))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 25), (yy + 29))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 26), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 26), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 17))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 18))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 19))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 28))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 26), (yy + 29))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 16))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 771, (xx + 27), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 27), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 28))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 27), (yy + 29))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 740, (xx + 28), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 14))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 15))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 27))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 28))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 28), (yy + 29))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 29), (yy + 20))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 29), (yy + 21))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 29), (yy + 22))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 29), (yy + 23))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 29), (yy + 24))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 29), (yy + 25))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 29), (yy + 26))
    tilemap_set(o.layer_tileset_floor_indoor, 739, (xx + 29), (yy + 27))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 1), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 2), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 770, (xx + 2), (yy + 10))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 3), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 3), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 4), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 4), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 5), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 5), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 768, (xx + 5), (yy + 14))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 6), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 6), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 768, (xx + 6), (yy + 15))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 7), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 7), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 7), (yy + 15))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 8), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 8), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 768, (xx + 8), (yy + 16))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 9), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 9), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 9), (yy + 16))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 10), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 10), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 768, (xx + 10), (yy + 18))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 11), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 11), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 768, (xx + 11), (yy + 20))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 12), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 770, (xx + 12), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 768, (xx + 12), (yy + 22))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 13), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 770, (xx + 13), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 13), (yy + 22))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 14), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 770, (xx + 14), (yy + 22))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 15), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 15), (yy + 20))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 16), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 768, (xx + 16), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 16), (yy + 20))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 17), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 17), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 17), (yy + 20))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 18), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 18), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 18), (yy + 20))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 19), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 768, (xx + 19), (yy + 10))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 19), (yy + 20))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 20), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 20), (yy + 10))
    tilemap_set(o.layer_tileset_wall_below_indoor, 768, (xx + 20), (yy + 22))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 21), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 768, (xx + 21), (yy + 13))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 21), (yy + 22))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 22), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 22), (yy + 13))
    tilemap_set(o.layer_tileset_wall_below_indoor, 770, (xx + 22), (yy + 22))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 23), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 770, (xx + 23), (yy + 13))
    tilemap_set(o.layer_tileset_wall_below_indoor, 770, (xx + 23), (yy + 20))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 24), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 24), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 770, (xx + 24), (yy + 19))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 25), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 770, (xx + 25), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 26), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 27), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 768, (xx + 27), (yy + 19))
    tilemap_set(o.layer_tileset_wall_below_indoor, 769, (xx + 28), (yy + 2))
    tilemap_set(o.layer_tileset_wall_below_indoor, 768, (xx + 28), (yy + 9))
    tilemap_set(o.layer_tileset_wall_below_indoor, 768, (xx + 28), (yy + 20))
    tilemap_set(o.layer_tileset_wall_above_indoor, 675, (xx + 0), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 0), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 0), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 0), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 0), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 1), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 1), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 1), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 675, (xx + 1), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 1), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 1), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 1), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 1), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 1), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 1), (yy + 15))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 1), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 2), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 2), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 675, (xx + 2), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 738, (xx + 2), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 2), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 2), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 2), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 2), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 2), (yy + 20))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 2), (yy + 21))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 2), (yy + 22))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 3), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 3), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 3), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 3), (yy + 22))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 4), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 4), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 4), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 4), (yy + 22))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 4), (yy + 23))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 5), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 5), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 5), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 672, (xx + 5), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 736, (xx + 5), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 5), (yy + 23))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 5), (yy + 24))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 6), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 6), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 6), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 6), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 676, (xx + 6), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 736, (xx + 6), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 6), (yy + 24))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 6), (yy + 25))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 7), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 7), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 7), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 7), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 7), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 7), (yy + 25))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 7), (yy + 26))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 8), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 8), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 8), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 8), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 676, (xx + 8), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 736, (xx + 8), (yy + 15))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 8), (yy + 26))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 9), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 672, (xx + 9), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 708, (xx + 9), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 9), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 9), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 9), (yy + 15))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 9), (yy + 26))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 10), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 672, (xx + 10), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 708, (xx + 10), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 10), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 10), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 676, (xx + 10), (yy + 15))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 10), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 736, (xx + 10), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 10), (yy + 26))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 11), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 11), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 11), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 11), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 676, (xx + 11), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 11), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 736, (xx + 11), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 11), (yy + 26))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 12), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 12), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 675, (xx + 12), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 738, (xx + 12), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 12), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 12), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 676, (xx + 12), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 12), (yy + 20))
    tilemap_set(o.layer_tileset_wall_above_indoor, 736, (xx + 12), (yy + 21))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 12), (yy + 26))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 13), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 13), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 13), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 738, (xx + 13), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 13), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 13), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 13), (yy + 15))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 13), (yy + 21))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 13), (yy + 26))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 13), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 14), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 14), (yy + 15))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 14), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 675, (xx + 14), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 14), (yy + 20))
    tilemap_set(o.layer_tileset_wall_above_indoor, 738, (xx + 14), (yy + 21))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 14), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 14), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 14), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 15), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 15), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 15), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 15), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 16), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 672, (xx + 16), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 736, (xx + 16), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 16), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 16), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 16), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 16), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 17), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 672, (xx + 17), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 708, (xx + 17), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 17), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 17), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 17), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 672, (xx + 17), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 17), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 708, (xx + 17), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 18), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 18), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 18), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 18), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 18), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 18), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 19), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 19), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 19), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 676, (xx + 19), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 19), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 736, (xx + 19), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 19), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 19), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 19), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 20), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 20), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 20), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 20), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 676, (xx + 20), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 20), (yy + 20))
    tilemap_set(o.layer_tileset_wall_above_indoor, 736, (xx + 20), (yy + 21))
    tilemap_set(o.layer_tileset_wall_above_indoor, 672, (xx + 20), (yy + 25))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 20), (yy + 26))
    tilemap_set(o.layer_tileset_wall_above_indoor, 708, (xx + 20), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 21), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 21), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 21), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 676, (xx + 21), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 21), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 21), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 736, (xx + 21), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 21), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 21), (yy + 21))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 21), (yy + 25))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 22), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 22), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 22), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 672, (xx + 22), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 708, (xx + 22), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 675, (xx + 22), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 22), (yy + 20))
    tilemap_set(o.layer_tileset_wall_above_indoor, 738, (xx + 22), (yy + 21))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 22), (yy + 25))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 22), (yy + 26))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 22), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 22), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 23), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 23), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 675, (xx + 23), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 23), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 23), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 23), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 738, (xx + 23), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 23), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 675, (xx + 23), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 738, (xx + 23), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 23), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 707, (xx + 23), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 24), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 24), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 24), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 24), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 706, (xx + 24), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 738, (xx + 24), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 24), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 25), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 674, (xx + 25), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 738, (xx + 25), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 25), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 26), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 26), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 27), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 672, (xx + 27), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 27), (yy + 17))
    tilemap_set(o.layer_tileset_wall_above_indoor, 736, (xx + 27), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 673, (xx + 27), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 737, (xx + 28), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 672, (xx + 28), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 28), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 736, (xx + 28), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 672, (xx + 28), (yy + 15))
    tilemap_set(o.layer_tileset_wall_above_indoor, 708, (xx + 28), (yy + 16))
    tilemap_set(o.layer_tileset_wall_above_indoor, 676, (xx + 28), (yy + 18))
    tilemap_set(o.layer_tileset_wall_above_indoor, 736, (xx + 28), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 672, (xx + 28), (yy + 28))
    tilemap_set(o.layer_tileset_wall_above_indoor, 708, (xx + 28), (yy + 29))
    tilemap_set(o.layer_tileset_wall_above_indoor, 676, (xx + 29), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 708, (xx + 29), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 676, (xx + 29), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 708, (xx + 29), (yy + 15))
    tilemap_set(o.layer_tileset_wall_above_indoor, 676, (xx + 29), (yy + 19))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 20))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 21))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 22))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 23))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 24))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 25))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 26))
    tilemap_set(o.layer_tileset_wall_above_indoor, 704, (xx + 29), (yy + 27))
    tilemap_set(o.layer_tileset_wall_above_indoor, 708, (xx + 29), (yy + 28))
    instance_create_depth(((xx * 16) + 368), ((yy * 16) + 240), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 416), ((yy * 16) + 336), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 416), ((yy * 16) + 416), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 320), ((yy * 16) + 384), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 384), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 368), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 304), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 224), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 176), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 272), ((yy * 16) + 208), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 432), ((yy * 16) + 208), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 400), ((yy * 16) + 80), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 240), ((yy * 16) + 64), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 80), 0, obj_quest_destroy_ghoul_lair_esplosione)
    instance_create_depth(((xx * 16) + 29), ((yy * 16) + 74), 0, obj_quest_destroy_ghoul_lair)
    return;
}

