d_group_id = 0
d_amount = 0
d_power = 0
d_faction = 0
d_object = 0
x_start = x
y_start = y
goto_x = 0
goto_y = 0
speed_path = 0.2
d_path = path_add()
move = 0
path_colore = make_color_rgb(irandom(255), irandom(255), irandom(255))
