function scr_check_item_position() //gml_Script_scr_check_item_position
{
    var camx = camera_get_view_x(view_camera[0])
    var camy = camera_get_view_y(view_camera[0])
    var inv_startx = (camx + 41)
    var inv_starty = (camy + 63)
    var primary_startx = (camx + 200)
    var primary_starty = (camy + 31)
    var secondary_startx = (camx + 200)
    var secondary_starty = (camy + 76)
    var loot_startx = (camx + 312)
    var loot_starty = (camy + 63)
    var trade_buy_startx = (camx + 192)
    var trade_buy_starty = (camy + 160)
    var trade_sell_startx = (camx + 192)
    var trade_sell_starty = (camy + 64)
    var quick_slot1_startx = (camx + 179)
    var quick_slot1_starty = (camy + 223)
    var quick_slot2_startx = (camx + 200)
    var quick_slot2_starty = (camy + 223)
    var quick_slot3_startx = (camx + 221)
    var quick_slot3_starty = (camy + 223)
    var quick_slot4_startx = (camx + 242)
    var quick_slot4_starty = (camy + 223)
    var quick_slot5_startx = (camx + 263)
    var quick_slot5_starty = (camy + 223)
    var quick_slot6_startx = (camx + 284)
    var quick_slot6_starty = (camy + 223)
    var backpack_startx = (camx + 248)
    var backpack_starty = (camy + 119)
    var armor_startx = (camx + 200)
    var armor_starty = (camy + 119)
    var headset_startx = (camx + 224)
    var headset_starty = (camy + 162)
    with (obj_item)
    {
        if (obj_player.trading == 0)
        {
            if scr_check_fast_position(x, y, 1, inv_startx, inv_starty, 128, 176, 0, 0)
                position = (0 << 0)
            else if scr_check_fast_position(x, y, 1, primary_startx, primary_starty, 80, 32, 0, 0)
                position = (1 << 0)
            else if scr_check_fast_position(x, y, 1, secondary_startx, secondary_starty, 80, 32, 0, 0)
                position = (2 << 0)
            else if scr_check_fast_position(x, y, 1, loot_startx, loot_starty, 128, 176, 0, 0)
                position = (3 << 0)
            else if scr_check_fast_position(x, y, 1, armor_startx, armor_starty, 32, 32, 0, 0)
                position = (11 << 0)
            else if scr_check_fast_position(x, y, 1, backpack_startx, backpack_starty, 32, 32, 0, 0)
                position = (10 << 0)
            else if scr_check_fast_position(x, y, 1, headset_startx, headset_starty, 32, 32, 0, 0)
                position = (12 << 0)
            else if scr_check_fast_position(x, y, 1, quick_slot1_startx, quick_slot1_starty, 16, 16, 0, 0)
                position = (4 << 0)
            else if scr_check_fast_position(x, y, 1, quick_slot2_startx, quick_slot2_starty, 16, 16, 0, 0)
                position = (5 << 0)
            else if scr_check_fast_position(x, y, 1, quick_slot3_startx, quick_slot3_starty, 16, 16, 0, 0)
                position = (6 << 0)
            else if scr_check_fast_position(x, y, 1, quick_slot4_startx, quick_slot4_starty, 16, 16, 0, 0)
                position = (7 << 0)
            else if scr_check_fast_position(x, y, 1, quick_slot5_startx, quick_slot5_starty, 16, 16, 0, 0)
                position = (8 << 0)
            else if scr_check_fast_position(x, y, 1, quick_slot6_startx, quick_slot6_starty, 16, 16, 0, 0)
                position = (9 << 0)
        }
        if (obj_player.trading == 1)
        {
            if (prev_position == -1)
            {
                if scr_check_fast_position(x, y, 2, inv_startx, inv_starty, 128, 176, 0, 0)
                    position = (0 << 0)
                else if scr_check_fast_position(x, y, 2, loot_startx, loot_starty, 128, 176, 0, 0)
                    position = (3 << 0)
                else if scr_check_fast_position(x, y, 2, trade_buy_startx, trade_buy_starty, 96, 80, 0, 0)
                    position = (13 << 0)
                else if scr_check_fast_position(x, y, 2, trade_sell_startx, trade_sell_starty, 96, 80, 0, 0)
                    position = (14 << 0)
            }
        }
    }
    scr_sistema_equip()
    return;
}

