function lista_npc() //gml_Script_lista_npc
{
    var bandit_list = ds_list_create()
    ds_list_add(bandit_list, (34 << 0), (3 << 0), (47 << 0), (23 << 0), (23 << 0), (80 << 0), (64 << 0), (64 << 0), (28 << 0), (28 << 0))
    ds_list_shuffle(bandit_list)
    novice_bandit_arma = ds_list_find_value(bandit_list, 0)
    var bandit_regular_list = ds_list_create()
    ds_list_add(bandit_regular_list, (38 << 0), (47 << 0), (47 << 0), (47 << 0), (61 << 0), (80 << 0), (55 << 0), (55 << 0), (87 << 0))
    ds_list_shuffle(bandit_regular_list)
    regular_bandit_arma = ds_list_find_value(bandit_regular_list, 0)
    var bandit_expert_list = ds_list_create()
    ds_list_add(bandit_expert_list, (38 << 0), (48 << 0), (47 << 0), (61 << 0), (62 << 0), (81 << 0), (14 << 0), (55 << 0), (65 << 0), (87 << 0), (36 << 0))
    ds_list_shuffle(bandit_expert_list)
    expert_bandit_arma = ds_list_find_value(bandit_expert_list, 0)
    var boss_guard_arma = choose((47 << 0), (61 << 0))
    var boss_arma = (50 << 0)
    var boss_arman_arma = (598 << 0)
    var boss_killa_arma = (592 << 0)
    var loner_2_list = ds_list_create()
    ds_list_add(loner_2_list, (47 << 0), (61 << 0), (54 << 0), (77 << 0), (36 << 0), (21 << 0), (87 << 0))
    ds_list_shuffle(loner_2_list)
    var arma_loner_2 = ds_list_find_value(loner_2_list, 0)
    var loner_novice_list = ds_list_create()
    ds_list_add(loner_novice_list, (38 << 0), (4 << 0), (47 << 0), (61 << 0), (80 << 0), (14 << 0), (55 << 0), (64 << 0), (87 << 0), (36 << 0), (3 << 0))
    ds_list_shuffle(loner_novice_list)
    loner_novice_arma = ds_list_find_value(loner_novice_list, 0)
    var green_army_soldier_list = ds_list_create()
    ds_list_add(green_army_soldier_list, (47 << 0), (61 << 0), (81 << 0), (48 << 0), (80 << 0), (14 << 0), (55 << 0), (64 << 0), (87 << 0), (36 << 0), (62 << 0), (39 << 0), (65 << 0), (50 << 0), (77 << 0))
    ds_list_shuffle(green_army_soldier_list)
    green_army1_arma = ds_list_find_value(green_army_soldier_list, 0)
    var crimson_soldier_list = ds_list_create()
    ds_list_add(crimson_soldier_list, (24 << 0), (17 << 0), (36 << 0), (58 << 0), (67 << 0), (9 << 0), (84 << 0), (74 << 0), (39 << 0), (91 << 0), (33 << 0), (576 << 0))
    ds_list_shuffle(crimson_soldier_list)
    crimson_arma = ds_list_find_value(crimson_soldier_list, 0)
    var mercenary_list = ds_list_create()
    ds_list_add(mercenary_list, (15 << 0), (6 << 0), (9 << 0), (26 << 0), (17 << 0), (19 << 0), (30 << 0), (67 << 0), (72 << 0), (74 << 0), (83 << 0), (84 << 0), (70 << 0), (59 << 0))
    ds_list_shuffle(mercenary_list)
    mercenary_arma = ds_list_find_value(mercenary_list, 0)
    var bandit_name = scr_generation_name(0)
    var bandit_cognome = scr_generation_name(1)
    var bandit_nome_completo = ((bandit_name + " ") + bandit_cognome)
    var eng_name = scr_generation_name_eng(0)
    var eng_last_name = scr_generation_name_eng(1)
    var eng_name_complete = ((eng_name + " ") + eng_last_name)
    npc_human_alert_distance = 230
    npc_human_alert_radius = 90
    npc_human_min_distance = 90
    npc_power[(1 << 0)] = 10
    npc_power[(3 << 0)] = 16
    npc_power[(4 << 0)] = 25
    npc_power[(5 << 0)] = 40
    npc_power[(6 << 0)] = 25
    npc_power[(7 << 0)] = 70
    npc_power[(9 << 0)] = 12
    npc_power[(10 << 0)] = 30
    npc_power[(11 << 0)] = 30
    npc_power[(13 << 0)] = 28
    npc_power[(14 << 0)] = 40
    npc_power[(15 << 0)] = 50
    npc_power[(20 << 0)] = 100
    npc_power[(21 << 0)] = 28
    npc_power[(22 << 0)] = 35
    npc_power[(23 << 0)] = 24
    npc_power[(24 << 0)] = 26
    npc_power[(25 << 0)] = 10
    npc_power[(26 << 0)] = 22
    npc_power[(28 << 0)] = 14
    npc_power[(33 << 0)] = 4
    npc_power[(34 << 0)] = 12
    npc_power[(35 << 0)] = 35
    npc_power[(36 << 0)] = 100
    npc_power[(37 << 0)] = 120
    npc_power[(38 << 0)] = 70
    npc_power[(39 << 0)] = 70
    npc_power[(0 << 0)] = 0
    npc_power[(2 << 0)] = 0
    npc_power[(27 << 0)] = 22
    npc_power[(29 << 0)] = 14
    npc_power[(30 << 0)] = 14
    npc_power[(16 << 0)] = 10
    npc_power[(17 << 0)] = 10
    npc_power[(18 << 0)] = 10
    npc_power[(19 << 0)] = 10
    npc_power[(47 << 0)] = 100
    npc_power[(31 << 0)] = 0
    npc_power[(32 << 0)] = 0
    npc_power[(40 << 0)] = 0
    npc_power[(41 << 0)] = 0
    npc_power[(42 << 0)] = 0
    npc_power[(43 << 0)] = 0
    npc_power[(44 << 0)] = 0
    npc_power[(45 << 0)] = 0
    npc_power[(46 << 0)] = 0
    npc_power[(48 << 0)] = 0
    npc_power[(49 << 0)] = 0
    npc_power[(50 << 0)] = 0
    npc_power[(51 << 0)] = 0
    npc_power[(52 << 0)] = 0
    npc_power[(53 << 0)] = 0
    npc_power[(54 << 0)] = 0
    npc_power[(55 << 0)] = 0
    npc_power[(56 << 0)] = 0
    npc_power[(57 << 0)] = 0
    npc_power[(58 << 0)] = 0
    npc_power[(59 << 0)] = 0
    npc_power[(60 << 0)] = 0
    npc_power[(61 << 0)] = 0
    npc_power[(62 << 0)] = 0
    npc_power[(63 << 0)] = 0
    npc_power[(64 << 0)] = 0
    npc_power[(65 << 0)] = 0
    npc_power[(66 << 0)] = 0
    a = (0 << 0)
    npc_my_id[a] = a
    npc_name[a] = bandit_nome_completo
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (10 << 0)
    npc_faction[a] = (1 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (416 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 70
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 48
    npc_sprite_move[a] = 49
    npc_sprite_dead[a] = 50
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0
    npc_spd_alerted[a] = 0
    npc_prob_move[a] = 0
    npc_prob_idle[a] = 0
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (0 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = 3
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (1 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("bandit " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (6 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = novice_bandit_arma
    npc_armor[a] = (420 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 2.7
    npc_hp[a] = 40
    npc_esperienza[a] = 10
    npc_chest_dropped[a] = (24 << 0)
    npc_sprite_idle[a] = 25
    npc_sprite_move[a] = 26
    npc_sprite_dead[a] = 27
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 0.3
    npc_prob_attack[a] = 2.1
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (3 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("bandit " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (6 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = regular_bandit_arma
    npc_armor[a] = (421 << 0)
    npc_ammo_value[a] = 2
    npc_aim_factor[a] = 2.5
    npc_hp[a] = 50
    npc_esperienza[a] = 18
    npc_chest_dropped[a] = (24 << 0)
    npc_sprite_idle[a] = 22
    npc_sprite_move[a] = 23
    npc_sprite_dead[a] = 24
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 0.3
    npc_prob_attack[a] = 2
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (4 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("bandit " + bandit_nome_completo)
    npc_arma[a] = expert_bandit_arma
    npc_armor[a] = (421 << 0)
    npc_ammo_value[a] = 3
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (6 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_aim_factor[a] = 2
    npc_hp[a] = 55
    npc_esperienza[a] = 18
    npc_chest_dropped[a] = (24 << 0)
    npc_sprite_idle[a] = 22
    npc_sprite_move[a] = 23
    npc_sprite_dead[a] = 24
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 0.3
    npc_prob_attack[a] = 2
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (6 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Lazar's guard"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (6 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = boss_guard_arma
    npc_armor[a] = (421 << 0)
    npc_ammo_value[a] = 3
    npc_aim_factor[a] = 1.5
    npc_hp[a] = 75
    npc_esperienza[a] = 30
    npc_chest_dropped[a] = (24 << 0)
    npc_sprite_idle[a] = 22
    npc_sprite_move[a] = 23
    npc_sprite_dead[a] = 24
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 0.3
    npc_prob_attack[a] = 1
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = 200
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (5 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Lazar"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (6 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = boss_arma
    npc_armor[a] = (426 << 0)
    npc_ammo_value[a] = 4
    npc_aim_factor[a] = 1
    npc_hp[a] = 120
    npc_esperienza[a] = 50
    npc_chest_dropped[a] = (25 << 0)
    npc_sprite_idle[a] = 28
    npc_sprite_move[a] = 29
    npc_sprite_dead[a] = 30
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 0.3
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = 200
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (7 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Arman"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (8 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = boss_arman_arma
    npc_armor[a] = (584 << 0)
    npc_ammo_value[a] = 4
    npc_aim_factor[a] = 0.8
    npc_hp[a] = 120
    npc_esperienza[a] = 50
    npc_chest_dropped[a] = (26 << 0)
    npc_sprite_idle[a] = 193
    npc_sprite_move[a] = 194
    npc_sprite_dead[a] = 195
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.5
    npc_spd_alerted[a] = 1.2
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 0.3
    npc_prob_attack[a] = 4
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = 400
    npc_player_distance_attack[a] = 320
    npc_alert_radius[a] = 140
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 180
    a = (8 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Kibba"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (8 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = boss_killa_arma
    npc_armor[a] = (597 << 0)
    npc_ammo_value[a] = 4
    npc_aim_factor[a] = 0.8
    npc_hp[a] = 120
    npc_esperienza[a] = 70
    npc_chest_dropped[a] = (27 << 0)
    npc_sprite_idle[a] = 196
    npc_sprite_move[a] = 197
    npc_sprite_dead[a] = 198
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.5
    npc_spd_alerted[a] = 1.2
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 0.3
    npc_prob_attack[a] = 1
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = 400
    npc_player_distance_attack[a] = 320
    npc_alert_radius[a] = 140
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 180
    a = (9 << 0)
    npc_my_id[a] = a
    npc_name[a] = bandit_nome_completo
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (11 << 0)
    npc_faction[a] = (1 << 0)
    npc_arma[a] = novice_bandit_arma
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 2
    npc_footstep_sound[a] = (1 << 0)
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 48
    npc_sprite_move[a] = 49
    npc_sprite_dead[a] = 50
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (10 << 0)
    npc_my_id[a] = a
    npc_name[a] = bandit_nome_completo
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (10 << 0)
    npc_faction[a] = (1 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = regular_bandit_arma
    npc_armor[a] = (418 << 0)
    npc_ammo_value[a] = 3
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 114
    npc_sprite_move[a] = 115
    npc_sprite_dead[a] = 116
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (11 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("Hunter " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (10 << 0)
    npc_faction[a] = (8 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = regular_bandit_arma
    npc_armor[a] = (418 << 0)
    npc_ammo_value[a] = choose(2, 2, 3, 3, 3, 4, 4)
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 55
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 114
    npc_sprite_move[a] = 115
    npc_sprite_dead[a] = 116
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (12 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("Hunter " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (10 << 0)
    npc_faction[a] = (8 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = arma_loner_2
    npc_armor[a] = (419 << 0)
    npc_ammo_value[a] = 4
    npc_aim_factor[a] = 1.2
    npc_hp[a] = 65
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 117
    npc_sprite_move[a] = 118
    npc_sprite_dead[a] = 119
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.3
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (13 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("Soldier " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (8 << 0)
    npc_faction[a] = (2 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = regular_bandit_arma
    npc_armor[a] = choose((413 << 0), (414 << 0))
    npc_ammo_value[a] = 3
    npc_aim_factor[a] = 2
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 60
    npc_sprite_move[a] = 61
    npc_sprite_dead[a] = 62
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (14 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("Soldier " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (1 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (64 << 0)
    npc_armor[a] = (413 << 0)
    npc_ammo_value[a] = 0
    npc_aim_factor[a] = 3.5
    npc_hp[a] = 80
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 60
    npc_sprite_move[a] = 61
    npc_sprite_dead[a] = 62
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0
    npc_spd_alerted[a] = 0
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = (2.7 + random_range(-0.2, 0.3))
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (15 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("Captain " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (26 << 0)
    npc_faction[a] = (1 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (61 << 0)
    npc_armor[a] = (413 << 0)
    npc_ammo_value[a] = 0
    npc_aim_factor[a] = 2
    npc_hp[a] = 80
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 63
    npc_sprite_move[a] = 64
    npc_sprite_dead[a] = 65
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0
    npc_spd_alerted[a] = 0
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.2
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (21 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("Crimson " + eng_name_complete)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (8 << 0)
    npc_faction[a] = (3 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = crimson_arma
    npc_armor[a] = choose((416 << 0), (417 << 0))
    npc_ammo_value[a] = 3
    npc_aim_factor[a] = 2
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (38 << 0)
    npc_sprite_idle[a] = 56
    npc_sprite_move[a] = 57
    npc_sprite_dead[a] = 58
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (22 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("Mercenary " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (8 << 0)
    npc_faction[a] = (5 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = mercenary_arma
    npc_armor[a] = (426 << 0)
    npc_ammo_value[a] = 3
    npc_aim_factor[a] = 1.5
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 76
    npc_sprite_move[a] = 77
    npc_sprite_dead[a] = 78
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (23 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("scientist " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (8 << 0)
    npc_faction[a] = (4 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = novice_bandit_arma
    npc_armor[a] = (422 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.5
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 67
    npc_sprite_move[a] = 68
    npc_sprite_dead[a] = 69
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (24 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("scientist " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (8 << 0)
    npc_faction[a] = (4 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = novice_bandit_arma
    npc_armor[a] = (423 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.5
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 70
    npc_sprite_move[a] = 71
    npc_sprite_dead[a] = 72
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (60 << 0)
    npc_my_id[a] = a
    npc_name[a] = "chief scientist Isaak Fedorov"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (27 << 0)
    npc_faction[a] = (4 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = novice_bandit_arma
    npc_armor[a] = (423 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.5
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 73
    npc_sprite_move[a] = 74
    npc_sprite_dead[a] = 75
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (26 << 0)
    npc_state_alert[a] = (26 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (64 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Unknown"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (28 << 0)
    npc_faction[a] = (1 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (61 << 0)
    npc_armor[a] = (428 << 0)
    npc_ammo_value[a] = 4
    npc_aim_factor[a] = 1
    npc_hp[a] = 500
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 162
    npc_sprite_move[a] = 163
    npc_sprite_dead[a] = 164
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (19 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (30 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Zombie"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (7 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = choose((34 << 0), (3 << 0), (23 << 0))
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 2.5
    npc_hp[a] = 45
    npc_esperienza[a] = 8
    npc_chest_dropped[a] = (46 << 0)
    npc_sprite_idle[a] = 87
    npc_sprite_move[a] = 88
    npc_sprite_dead[a] = 89
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.25
    npc_prob_move[a] = 0.1
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 2
    npc_state_patrol[a] = (9 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 180
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (25 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Wolf"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (7 << 0)
    npc_footstep_sound[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_damage_melee[a] = 20
    npc_hp[a] = 45
    npc_esperienza[a] = 6
    npc_chest_dropped[a] = (41 << 0)
    npc_sprite_idle[a] = 177
    npc_sprite_move[a] = 179
    npc_sprite_dead[a] = 187
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 1.5
    npc_spd_not_alerted[a] = 0.75
    npc_spd_alerted[a] = 2
    npc_prob_move[a] = 2
    npc_prob_idle[a] = 0.05
    npc_prob_attack[a] = 2
    npc_state_patrol[a] = (42 << 0)
    npc_state_alert[a] = (48 << 0)
    npc_player_distance_alert[a] = 150
    npc_player_distance_attack[a] = 80
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (34 << 0)
    npc_my_id[a] = a
    npc_name[a] = "ghoul"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (7 << 0)
    npc_footstep_sound[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_damage_melee[a] = 15
    npc_hp[a] = 45
    npc_esperienza[a] = 7
    npc_chest_dropped[a] = (43 << 0)
    npc_sprite_idle[a] = 150
    npc_sprite_move[a] = 151
    npc_sprite_dead[a] = 153
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 1
    npc_spd_not_alerted[a] = 0.75
    npc_spd_alerted[a] = 1.5
    npc_prob_move[a] = 1
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 4
    npc_state_patrol[a] = (35 << 0)
    npc_state_alert[a] = (36 << 0)
    npc_player_distance_alert[a] = 150
    npc_player_distance_attack[a] = 80
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (35 << 0)
    npc_my_id[a] = a
    npc_name[a] = "blink"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (7 << 0)
    npc_footstep_sound[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_damage_melee[a] = 40
    npc_hp[a] = 35
    npc_esperienza[a] = 15
    npc_chest_dropped[a] = (49 << 0)
    npc_sprite_idle[a] = 170
    npc_sprite_move[a] = 171
    npc_sprite_dead[a] = 173
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 1.1
    npc_spd_not_alerted[a] = 1
    npc_spd_alerted[a] = 2.5
    npc_prob_move[a] = 2
    npc_prob_idle[a] = 0.05
    npc_prob_attack[a] = 6
    npc_state_patrol[a] = (35 << 0)
    npc_state_alert[a] = (36 << 0)
    npc_player_distance_alert[a] = 240
    npc_player_distance_attack[a] = 80
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 80
    a = (37 << 0)
    npc_my_id[a] = a
    npc_name[a] = "big"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (7 << 0)
    npc_footstep_sound[a] = (5 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_damage_melee[a] = 30
    npc_hp[a] = 270
    npc_esperienza[a] = 120
    npc_chest_dropped[a] = (47 << 0)
    npc_sprite_idle[a] = 154
    npc_sprite_move[a] = 155
    npc_sprite_dead[a] = 158
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 1
    npc_spd_not_alerted[a] = 1
    npc_spd_alerted[a] = 2.5
    npc_prob_move[a] = 1
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 1
    npc_state_patrol[a] = (35 << 0)
    npc_state_alert[a] = (36 << 0)
    npc_player_distance_alert[a] = 240
    npc_player_distance_attack[a] = 80
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (33 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Rat"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (7 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_damage_melee[a] = 5
    npc_hp[a] = 15
    npc_esperienza[a] = 2
    npc_chest_dropped[a] = (42 << 0)
    npc_sprite_idle[a] = 147
    npc_sprite_move[a] = 148
    npc_sprite_dead[a] = 149
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 1
    npc_spd_not_alerted[a] = 0.75
    npc_spd_alerted[a] = 1.5
    npc_prob_move[a] = 2
    npc_prob_idle[a] = 2
    npc_prob_attack[a] = 2
    npc_state_patrol[a] = (35 << 0)
    npc_state_alert[a] = (36 << 0)
    npc_player_distance_alert[a] = 150
    npc_player_distance_attack[a] = 80
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (26 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Boar"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (7 << 0)
    npc_footstep_sound[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_damage_melee[a] = 35
    npc_hp[a] = 65
    npc_esperienza[a] = 18
    npc_chest_dropped[a] = (44 << 0)
    npc_sprite_idle[a] = 96
    npc_sprite_move[a] = 97
    npc_sprite_dead[a] = 99
    npc_ims_idle[a] = 0.4
    npc_ims_move[a] = 1
    npc_spd_not_alerted[a] = 0.5
    npc_spd_alerted[a] = 1.25
    npc_prob_move[a] = 2
    npc_prob_idle[a] = 2
    npc_prob_attack[a] = 6
    npc_state_patrol[a] = (35 << 0)
    npc_state_alert[a] = (38 << 0)
    npc_player_distance_alert[a] = 164
    npc_player_distance_attack[a] = 80
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (27 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Mutated Boar"
    npc_damage_melee[a] = 21
    npc_hp[a] = 120
    npc_esperienza[a] = 28
    npc_faction[a] = (7 << 0)
    npc_footstep_sound[a] = (2 << 0)
    npc_chest_dropped[a] = (44 << 0)
    npc_sprite_idle[a] = 102
    npc_sprite_move[a] = 101
    npc_sprite_dead[a] = 103
    npc_ims_idle[a] = 0.4
    npc_ims_move[a] = 1
    npc_spd_not_alerted[a] = 0.5
    npc_spd_alerted[a] = 1.25
    npc_prob_move[a] = 2
    npc_prob_idle[a] = 2
    npc_prob_attack[a] = 6
    npc_state_patrol[a] = (35 << 0)
    npc_state_alert[a] = (38 << 0)
    npc_player_distance_alert[a] = 164
    npc_player_distance_attack[a] = 80
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (29 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Spine"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (7 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_damage_melee[a] = 6
    npc_hp[a] = 35
    npc_esperienza[a] = 16
    npc_chest_dropped[a] = (53 << 0)
    npc_sprite_idle[a] = 105
    npc_sprite_move[a] = 106
    npc_sprite_dead[a] = 107
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.75
    npc_spd_not_alerted[a] = 0.5
    npc_spd_alerted[a] = 1.5
    npc_prob_move[a] = 2
    npc_prob_idle[a] = 2
    npc_prob_attack[a] = 6
    npc_state_patrol[a] = (35 << 0)
    npc_state_alert[a] = (36 << 0)
    npc_player_distance_alert[a] = 150
    npc_player_distance_attack[a] = 80
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (28 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Mutated Spider"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (7 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_damage_melee[a] = 10
    npc_hp[a] = 35
    npc_esperienza[a] = 17
    npc_chest_dropped[a] = (48 << 0)
    npc_sprite_idle[a] = 93
    npc_sprite_move[a] = 94
    npc_sprite_dead[a] = 95
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 1
    npc_spd_not_alerted[a] = 0.75
    npc_spd_alerted[a] = 2
    npc_prob_move[a] = 2
    npc_prob_idle[a] = 2
    npc_prob_attack[a] = 2
    npc_state_patrol[a] = (35 << 0)
    npc_state_alert[a] = (36 << 0)
    npc_player_distance_alert[a] = 190
    npc_player_distance_attack[a] = 80
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (38 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Electrical anomaly"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (7 << 0)
    npc_footstep_sound[a] = (0 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_damage_melee[a] = 20
    npc_hp[a] = 250
    npc_esperienza[a] = 35
    npc_chest_dropped[a] = (56 << 0)
    npc_sprite_idle[a] = 1931
    npc_sprite_move[a] = 1931
    npc_sprite_dead[a] = 53
    npc_ims_idle[a] = 0.5
    npc_ims_move[a] = 0
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.5
    npc_prob_move[a] = 5
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 0.1
    npc_state_patrol[a] = (62 << 0)
    npc_state_alert[a] = (63 << 0)
    npc_player_distance_alert[a] = 110
    npc_player_distance_attack[a] = 80
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 80
    a = (39 << 0)
    npc_my_id[a] = a
    npc_name[a] = "anomaly_fire"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (7 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_damage_melee[a] = 20
    npc_hp[a] = 250
    npc_esperienza[a] = 35
    npc_chest_dropped[a] = (57 << 0)
    npc_sprite_idle[a] = 1931
    npc_sprite_move[a] = 1931
    npc_sprite_dead[a] = 54
    npc_ims_idle[a] = 0.5
    npc_ims_move[a] = 0
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 1
    npc_prob_move[a] = 5
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 0.1
    npc_state_patrol[a] = (60 << 0)
    npc_state_alert[a] = (61 << 0)
    npc_player_distance_alert[a] = 110
    npc_player_distance_attack[a] = 80
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 80
    a = (31 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Rabbit"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_damage_melee[a] = 0
    npc_hp[a] = 10
    npc_esperienza[a] = 2
    npc_chest_dropped[a] = (51 << 0)
    npc_sprite_idle[a] = 136
    npc_sprite_move[a] = 138
    npc_sprite_dead[a] = 139
    npc_ims_idle[a] = 0.5
    npc_ims_move[a] = 1
    npc_spd_not_alerted[a] = 0.75
    npc_spd_alerted[a] = 1.5
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 2
    npc_prob_attack[a] = 0.1
    npc_state_patrol[a] = (64 << 0)
    npc_state_alert[a] = (66 << 0)
    npc_player_distance_alert[a] = 64
    npc_player_distance_attack[a] = 80
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (32 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Crow"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_damage_melee[a] = 0
    npc_hp[a] = 10
    npc_esperienza[a] = 2
    npc_chest_dropped[a] = (52 << 0)
    npc_sprite_idle[a] = 140
    npc_sprite_move[a] = 142
    npc_sprite_dead[a] = 146
    npc_ims_idle[a] = 0.5
    npc_ims_move[a] = 1
    npc_spd_not_alerted[a] = 0.75
    npc_spd_alerted[a] = 1.5
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 2
    npc_prob_attack[a] = 0.1
    npc_state_patrol[a] = (67 << 0)
    npc_state_alert[a] = (71 << 0)
    npc_player_distance_alert[a] = 64
    npc_player_distance_attack[a] = 32
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 32
    a = (36 << 0)
    npc_my_id[a] = a
    npc_name[a] = "infestation"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (7 << 0)
    npc_footstep_sound[a] = (5 << 0)
    npc_armor[a] = (0 << 0)
    npc_damage_melee[a] = 0
    npc_hp[a] = 400
    npc_esperienza[a] = 120
    npc_chest_dropped[a] = (54 << 0)
    npc_sprite_idle[a] = 168
    npc_sprite_move[a] = 168
    npc_sprite_dead[a] = 169
    npc_ims_idle[a] = 0
    npc_ims_move[a] = 0
    npc_spd_not_alerted[a] = 0
    npc_spd_alerted[a] = 0
    npc_prob_move[a] = 1
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 1
    npc_state_patrol[a] = (75 << 0)
    npc_state_alert[a] = (75 << 0)
    npc_player_distance_alert[a] = 240
    npc_player_distance_attack[a] = 80
    npc_alert_radius[a] = 90
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (20 << 0)
    npc_my_id[a] = a
    npc_name[a] = eng_name_complete
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (29 << 0)
    npc_faction[a] = (3 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = crimson_arma
    npc_armor[a] = (417 << 0)
    npc_ammo_value[a] = 3
    npc_aim_factor[a] = 2
    npc_hp[a] = 80
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (38 << 0)
    npc_sprite_idle[a] = 56
    npc_sprite_move[a] = 57
    npc_sprite_dead[a] = 58
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (8 << 0)
    npc_state_alert[a] = (8 << 0)
    npc_player_distance_alert[a] = npc_human_alert_distance
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = npc_human_alert_radius
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (47 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Reynard Shepard"
    npc_trader_id[a] = (10 << 0)
    npc_speaker_id[a] = (30 << 0)
    npc_faction[a] = (3 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (417 << 0)
    npc_ammo_value[a] = 3
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (38 << 0)
    npc_sprite_idle[a] = 59
    npc_sprite_move[a] = 57
    npc_sprite_dead[a] = 58
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0
    npc_spd_alerted[a] = 0
    npc_prob_move[a] = 0
    npc_prob_idle[a] = 20
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (25 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = npc_human_min_distance
    a = (48 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Joel Emerson"
    npc_trader_id[a] = (11 << 0)
    npc_speaker_id[a] = (4 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 0
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (3 << 0)
    npc_sprite_idle[a] = 4
    npc_sprite_move[a] = 4
    npc_sprite_dead[a] = 4
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (0 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (68 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Daniel Baker"
    npc_trader_id[a] = (11 << 0)
    npc_speaker_id[a] = (4 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 0
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (3 << 0)
    npc_sprite_idle[a] = 4
    npc_sprite_move[a] = 4
    npc_sprite_dead[a] = 4
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (0 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (49 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Max Parker"
    npc_trader_id[a] = (12 << 0)
    npc_speaker_id[a] = (3 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 0
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (3 << 0)
    npc_sprite_idle[a] = 4
    npc_sprite_move[a] = 4
    npc_sprite_dead[a] = 4
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (1 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (62 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Igor Kuzmin"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (32 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 10
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (30 << 0)
    npc_sprite_idle[a] = 174
    npc_sprite_move[a] = 175
    npc_sprite_dead[a] = 176
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0
    npc_spd_alerted[a] = 0
    npc_prob_move[a] = 0
    npc_prob_idle[a] = 20
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (21 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (63 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Mr. Junk"
    npc_trader_id[a] = (8 << 0)
    npc_speaker_id[a] = (33 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 10
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (33 << 0)
    npc_sprite_idle[a] = 188
    npc_sprite_move[a] = 188
    npc_sprite_dead[a] = 189
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0
    npc_spd_alerted[a] = 0
    npc_prob_move[a] = 0
    npc_prob_idle[a] = 20
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (22 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (40 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Barman"
    npc_trader_id[a] = (4 << 0)
    npc_speaker_id[a] = (5 << 0)
    npc_faction[a] = (1 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 1931
    npc_sprite_move[a] = 1931
    npc_sprite_dead[a] = 1931
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (1 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (41 << 0)
    npc_my_id[a] = a
    npc_name[a] = "General Artemovich"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (1 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 63
    npc_sprite_move[a] = 61
    npc_sprite_dead[a] = 62
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (1 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (43 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Alexei Andreevich"
    npc_trader_id[a] = (1 << 0)
    npc_speaker_id[a] = (3 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 1931
    npc_sprite_move[a] = 1931
    npc_sprite_dead[a] = 1931
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (1 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (44 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Osip Andreevich"
    npc_trader_id[a] = (3 << 0)
    npc_speaker_id[a] = (3 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 1931
    npc_sprite_move[a] = 1931
    npc_sprite_dead[a] = 1931
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (1 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (42 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Henry Davies"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (2 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 59
    npc_sprite_move[a] = 57
    npc_sprite_dead[a] = 1931
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (1 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (45 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Riley Evans"
    npc_trader_id[a] = (2 << 0)
    npc_speaker_id[a] = (4 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 1931
    npc_sprite_move[a] = 1931
    npc_sprite_dead[a] = 1931
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (1 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (46 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Dimitriy Alexeev"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (36 << 0)
    npc_faction[a] = (1 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 1931
    npc_sprite_move[a] = 1931
    npc_sprite_dead[a] = 1931
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (1 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (52 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Engineer Volkov"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (9 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 126
    npc_sprite_move[a] = 127
    npc_sprite_dead[a] = 62
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (1 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (53 << 0)
    npc_my_id[a] = a
    npc_name[a] = "The Doctor"
    npc_trader_id[a] = (5 << 0)
    npc_speaker_id[a] = (6 << 0)
    npc_faction[a] = (4 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 1931
    npc_sprite_move[a] = 1931
    npc_sprite_dead[a] = 1931
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (1 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (51 << 0)
    npc_my_id[a] = a
    npc_name[a] = "The Guide"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (12 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.5
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 120
    npc_sprite_move[a] = 121
    npc_sprite_dead[a] = 50
    npc_ims_idle[a] = 0.15
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0
    npc_spd_alerted[a] = 0
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 0
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (4 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (50 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Conductor"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (16 << 0)
    npc_faction[a] = (1 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.5
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 160
    npc_sprite_move[a] = 161
    npc_sprite_dead[a] = 50
    npc_ims_idle[a] = 0.15
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0
    npc_spd_alerted[a] = 0
    npc_prob_move[a] = 0
    npc_prob_idle[a] = 0
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (4 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (67 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Sacriel"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (37 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (0 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 202
    npc_sprite_move[a] = 1931
    npc_sprite_dead[a] = 1931
    npc_ims_idle[a] = 0.15
    npc_ims_move[a] = 0
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (76 << 0)
    npc_state_alert[a] = (76 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (16 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("Soldier " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (21 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = choose((63 << 0), (49 << 0), (66 << 0), (52 << 0))
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 2
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 60
    npc_sprite_move[a] = 61
    npc_sprite_dead[a] = 62
    npc_ims_idle[a] = 0.15
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (3 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (17 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Soldier Yakim Borisov"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (22 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (61 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 2
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 60
    npc_sprite_move[a] = 61
    npc_sprite_dead[a] = 62
    npc_ims_idle[a] = 0.15
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (3 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (18 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Soldier Vadim Borisov"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (23 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (61 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 2
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 60
    npc_sprite_move[a] = 61
    npc_sprite_dead[a] = 62
    npc_ims_idle[a] = 0.15
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (3 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (19 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Soldier Kodiak Vlasov"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (24 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (63 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 2
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 60
    npc_sprite_move[a] = 61
    npc_sprite_dead[a] = 62
    npc_ims_idle[a] = 0.15
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (5 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (55 << 0)
    npc_my_id[a] = a
    npc_name[a] = bandit_nome_completo
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = novice_bandit_arma
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 48
    npc_sprite_move[a] = 49
    npc_sprite_dead[a] = 50
    npc_ims_idle[a] = 0.15
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (4 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (56 << 0)
    npc_my_id[a] = a
    npc_name[a] = bandit_nome_completo
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (1 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = green_army1_arma
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 114
    npc_sprite_move[a] = 115
    npc_sprite_dead[a] = 116
    npc_ims_idle[a] = 0.15
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (4 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (57 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("Soldier " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (2 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = green_army1_arma
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 2
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 60
    npc_sprite_move[a] = 61
    npc_sprite_dead[a] = 62
    npc_ims_idle[a] = 0.15
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (4 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (58 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("Crimson " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (3 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = crimson_arma
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 2
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 56
    npc_sprite_move[a] = 57
    npc_sprite_dead[a] = 58
    npc_ims_idle[a] = 0.15
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (4 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (59 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("scientist " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (4 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = green_army1_arma
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.5
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 67
    npc_sprite_move[a] = 68
    npc_sprite_dead[a] = 69
    npc_ims_idle[a] = 0.15
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.2
    npc_prob_idle[a] = 1
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (4 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (61 << 0)
    npc_my_id[a] = a
    npc_name[a] = ("Soldier " + bandit_nome_completo)
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (34 << 0)
    npc_faction[a] = (2 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = green_army1_arma
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 2
    npc_hp[a] = 60
    npc_esperienza[a] = 20
    npc_chest_dropped[a] = (36 << 0)
    npc_sprite_idle[a] = 60
    npc_sprite_move[a] = 61
    npc_sprite_dead[a] = 62
    npc_ims_idle[a] = 0.15
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0.5
    npc_prob_idle[a] = 0.2
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (1 << 0)
    npc_state_alert[a] = (11 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 64
    a = (65 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Viktor Tutorialovich"
    npc_trader_id[a] = (9 << 0)
    npc_speaker_id[a] = (35 << 0)
    npc_faction[a] = (9 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 60
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (29 << 0)
    npc_sprite_idle[a] = 76
    npc_sprite_move[a] = 77
    npc_sprite_dead[a] = 78
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0.25
    npc_spd_alerted[a] = 0.75
    npc_prob_move[a] = 0
    npc_prob_idle[a] = 0
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (1 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    a = (66 << 0)
    npc_my_id[a] = a
    npc_name[a] = "Viktor Tutorialovich"
    npc_trader_id[a] = (0 << 0)
    npc_speaker_id[a] = (0 << 0)
    npc_faction[a] = (6 << 0)
    npc_footstep_sound[a] = (1 << 0)
    npc_arma[a] = (2 << 0)
    npc_armor[a] = (0 << 0)
    npc_ammo_value[a] = 1
    npc_aim_factor[a] = 1.3
    npc_hp[a] = 150
    npc_esperienza[a] = 22
    npc_chest_dropped[a] = (24 << 0)
    npc_sprite_idle[a] = 25
    npc_sprite_move[a] = 26
    npc_sprite_dead[a] = 27
    npc_ims_idle[a] = 0.25
    npc_ims_move[a] = 0.5
    npc_spd_not_alerted[a] = 0
    npc_spd_alerted[a] = 0
    npc_prob_move[a] = 0
    npc_prob_idle[a] = 0
    npc_prob_attack[a] = 1.5
    npc_state_patrol[a] = (0 << 0)
    npc_player_distance_alert[a] = 250
    npc_player_distance_attack[a] = 230
    npc_alert_radius[a] = 60
    npc_alert_visual_distance[a] = npc_player_distance_alert[a]
    npc_alert_min_distance[a] = 120
    return;
}

