function scr_indoor_police_villaggio_1(argument0, argument1, argument2, argument3) //gml_Script_scr_indoor_police_villaggio_1
{
    var xx = argument0
    var yy = argument1
    var dest_x = argument2
    var dest_y = argument3
    var o = obj_map_generator
    scr_place_obj_map(265, ((xx * 16) + 161), ((yy * 16) + 127))
    scr_place_obj_map(265, ((xx * 16) + 145), ((yy * 16) + 127))
    scr_place_obj_map(268, ((xx * 16) + 80), ((yy * 16) + 47))
    scr_place_obj_map(274, ((xx * 16) + 97), ((yy * 16) + 47))
    scr_place_obj_map(111, ((xx * 16) + 204), ((yy * 16) + 151))
    scr_place_obj_map(111, ((xx * 16) + 204), ((yy * 16) + 184))
    scr_place_obj_map(111, ((xx * 16) + 205), ((yy * 16) + 215))
    scr_place_obj_map(135, ((xx * 16) + 192), ((yy * 16) + 207))
    scr_place_obj_map(135, ((xx * 16) + 192), ((yy * 16) + 175))
    scr_place_obj_map(135, ((xx * 16) + 192), ((yy * 16) + 143))
    scr_place_obj_map(96, ((xx * 16) + 132), ((yy * 16) + 218))
    scr_place_obj_map(96, ((xx * 16) + 132), ((yy * 16) + 170))
    scr_place_obj_map(96, ((xx * 16) + 132), ((yy * 16) + 202))
    scr_place_obj_map(96, ((xx * 16) + 132), ((yy * 16) + 186))
    scr_place_obj_map(23, ((xx * 16) + 120), ((yy * 16) + 135))
    scr_place_obj_map(23, ((xx * 16) + 43), ((yy * 16) + 136))
    scr_place_obj_map(98, ((xx * 16) + 104), ((yy * 16) + 68))
    scr_place_obj_map(98, ((xx * 16) + 88), ((yy * 16) + 68))
    scr_place_obj_map(100, ((xx * 16) + 96), ((yy * 16) + 96))
    scr_place_obj_map(276, ((xx * 16) + 28), ((yy * 16) + 136))
    scr_place_obj_map(98, ((xx * 16) + 112), ((yy * 16) + 135))
    scr_place_obj_map(98, ((xx * 16) + 104), ((yy * 16) + 135))
    scr_place_obj_map(98, ((xx * 16) + 96), ((yy * 16) + 135))
    scr_place_obj_map(98, ((xx * 16) + 88), ((yy * 16) + 135))
    scr_place_obj_map(278, ((xx * 16) + 208), ((yy * 16) + 95))
    scr_place_obj_map(280, ((xx * 16) + 192), ((yy * 16) + 95))
    scr_place_obj_map(279, ((xx * 16) + 176), ((yy * 16) + 95))
    scr_place_obj_map(279, ((xx * 16) + 160), ((yy * 16) + 95))
    scr_place_obj_map(277, ((xx * 16) + 144), ((yy * 16) + 95))
    scr_place_obj_map(268, ((xx * 16) + 80), ((yy * 16) + 199))
    scr_place_obj_map(116, ((xx * 16) + 37), ((yy * 16) + 197))
    scr_place_obj_map(116, ((xx * 16) + 23), ((yy * 16) + 197))
    instance_create_depth(((xx * 16) + 73), ((yy * 16) + 199), 0, obj_chest_bag)
    instance_create_depth(((xx * 16) + 24), ((yy * 16) + 143), 0, obj_chest_vending_machine)
    instance_create_depth(((xx * 16) + 219), ((yy * 16) + 78), 0, obj_chest_medication_box)
    instance_create_depth(((xx * 16) + 150), ((yy * 16) + 78), 0, obj_chest_medication_box)
    instance_create_depth(((xx * 16) + 200), ((yy * 16) + 47), 0, obj_weapon_box_common)
    instance_create_depth(((xx * 16) + 216), ((yy * 16) + 47), 0, obj_weapon_box_common)
    instance_create_depth(((xx * 16) + 185), ((yy * 16) + 47), 0, obj_weapon_box_rare)
    instance_create_depth(((xx * 16) + 168), ((yy * 16) + 47), 0, obj_chest_safe)
    instance_create_depth(((xx * 16) + 152), ((yy * 16) + 47), 0, obj_chest_safe)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 47), 0, obj_chest_cabinet)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 47), 0, obj_chest_cabinet)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 47), 0, obj_chest_cabinet)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 47), 0, obj_chest_cabinet)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 23), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 23), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 23), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 23), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 0), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 16), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 32), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 48), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 64), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 80), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 96), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 112), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 128), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 144), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 160), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 176), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 192), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 208), 0, obj_solid)
    instance_create_depth(((xx * 16) + 224), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 208), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 192), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 176), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 160), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 144), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 128), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 112), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 96), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 80), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 64), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 48), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 32), ((yy * 16) + 224), 0, obj_solid)
    instance_create_depth(((xx * 16) + 16), ((yy * 16) + 224), 0, obj_solid)
    var o_indoor = instance_create_depth(((xx * 16) + 160), ((yy * 16) + 207), 0, obj_indoor)
    o_indoor.tele_x = dest_x
    o_indoor.tele_y = dest_y
    var o_indoor2 = instance_create_depth((x + o.b_x[decor_id][image_index]), (y + o.b_y[decor_id][image_index]), 0, obj_indoor)
    o_indoor2.tele_x = (((xx * 16) + 8) + 160)
    o_indoor2.tele_y = (((yy * 16) + 5) + 207)
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 1), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 1), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 1), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 1), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 1), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 1), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 1), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 1), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 1), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 1), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 2), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 2), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 2), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 2), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 2), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 2), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 2), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 2), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 2), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 2), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 3), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 3), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 3), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 3), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 3), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 3), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 3), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 3), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 3), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 3), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 3), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 3), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 4), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 4), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 4), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 4), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 4), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 4), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 4), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 4), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 4), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 4), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 4), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 4), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 5), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 5), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 5), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 5), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 5), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 5), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 5), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 5), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 5), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 5), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 6), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 6), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 6), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 6), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 6), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 6), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 6), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 6), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 6), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 6), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 7), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 7), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 7), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 7), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 7), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 7), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 8), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 8), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 8), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 8), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 8), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 8), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 9), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 9), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 9), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 9), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 9), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 9), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 9), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 9), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 9), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 9), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 9), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 9), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 10), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 10), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 10), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 10), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 10), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 10), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 10), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 10), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 10), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 10), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 10), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 10), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 11), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 11), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 11), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 11), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 11), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 11), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 11), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 11), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 11), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 11), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 11), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 11), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 12), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 12), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 12), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 12), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 12), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 12), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 12), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 12), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 12), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 12), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 12), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 12), (yy + 13))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 13), (yy + 2))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 13), (yy + 3))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 13), (yy + 4))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 13), (yy + 5))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 13), (yy + 6))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 13), (yy + 7))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 13), (yy + 8))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 13), (yy + 9))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 13), (yy + 10))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 13), (yy + 11))
    tilemap_set(o.layer_tileset_floor_indoor, 616, (xx + 13), (yy + 12))
    tilemap_set(o.layer_tileset_floor_indoor, 648, (xx + 13), (yy + 13))
    tilemap_set(o.layer_tileset_wall_below_indoor, 774, (xx + 1), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 773, (xx + 1), (yy + 7))
    tilemap_set(o.layer_tileset_wall_below_indoor, 774, (xx + 1), (yy + 11))
    tilemap_set(o.layer_tileset_wall_below_indoor, 775, (xx + 2), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 776, (xx + 2), (yy + 7))
    tilemap_set(o.layer_tileset_wall_below_indoor, 776, (xx + 2), (yy + 11))
    tilemap_set(o.layer_tileset_wall_below_indoor, 774, (xx + 3), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 775, (xx + 4), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 773, (xx + 4), (yy + 11))
    tilemap_set(o.layer_tileset_wall_below_indoor, 774, (xx + 5), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 773, (xx + 5), (yy + 7))
    tilemap_set(o.layer_tileset_wall_below_indoor, 775, (xx + 5), (yy + 11))
    tilemap_set(o.layer_tileset_wall_below_indoor, 775, (xx + 6), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 774, (xx + 6), (yy + 7))
    tilemap_set(o.layer_tileset_wall_below_indoor, 775, (xx + 7), (yy + 7))
    tilemap_set(o.layer_tileset_wall_below_indoor, 776, (xx + 8), (yy + 7))
    tilemap_set(o.layer_tileset_wall_below_indoor, 774, (xx + 9), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 775, (xx + 10), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 774, (xx + 11), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 775, (xx + 12), (yy + 1))
    tilemap_set(o.layer_tileset_wall_below_indoor, 774, (xx + 13), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 805, (xx + 0), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 0), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 0), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 0), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 0), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 837, (xx + 0), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 805, (xx + 0), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 0), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 0), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 837, (xx + 0), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 805, (xx + 0), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 0), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 0), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 837, (xx + 0), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 0), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 742, (xx + 1), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 1), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 741, (xx + 1), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 679, (xx + 1), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 742, (xx + 1), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 1), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 1), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 743, (xx + 2), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 680, (xx + 2), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 744, (xx + 2), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 680, (xx + 2), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 744, (xx + 2), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 2), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 2), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 742, (xx + 3), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 3), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 3), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 743, (xx + 4), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 677, (xx + 4), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 741, (xx + 4), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 4), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 4), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 742, (xx + 5), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 677, (xx + 5), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 741, (xx + 5), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 5), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 743, (xx + 5), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 5), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 5), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 743, (xx + 6), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 6), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 742, (xx + 6), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 6), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 806, (xx + 6), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 6), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 6), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 838, (xx + 6), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 6), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 806, (xx + 7), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 7), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 7), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 7), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 7), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 838, (xx + 7), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 743, (xx + 7), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 680, (xx + 7), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 7), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 7), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 7), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 837, (xx + 7), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 7), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 805, (xx + 8), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 8), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 8), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 8), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 8), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 712, (xx + 8), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 744, (xx + 8), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 8), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 8), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 742, (xx + 9), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 9), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 9), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 743, (xx + 10), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 10), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 10), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 742, (xx + 11), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 11), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 11), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 743, (xx + 12), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 12), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 12), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 742, (xx + 13), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 678, (xx + 13), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 13), (yy + 14))
    tilemap_set(o.layer_tileset_wall_above_indoor, 806, (xx + 14), (yy + 0))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 14), (yy + 1))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 14), (yy + 2))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 14), (yy + 3))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 14), (yy + 4))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 14), (yy + 5))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 14), (yy + 6))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 14), (yy + 7))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 14), (yy + 8))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 14), (yy + 9))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 14), (yy + 10))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 14), (yy + 11))
    tilemap_set(o.layer_tileset_wall_above_indoor, 709, (xx + 14), (yy + 12))
    tilemap_set(o.layer_tileset_wall_above_indoor, 838, (xx + 14), (yy + 13))
    tilemap_set(o.layer_tileset_wall_above_indoor, 710, (xx + 14), (yy + 14))
    instance_create_depth(((xx * 16) + 151), ((yy * 16) + 98), 0, obj_quest_document_2)
    instance_create_depth(((xx * 16) + 200), ((yy * 16) + 92), 0, obj_door_stazione_polizia_villaggio)
    return;
}

