global.rain = 0
var a = (0 << 0)
particles_system[a] = part_system_create()
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1952, 0, 0, 1)
part_type_speed(particles_type[a], 1, 3, -0.2, 0)
part_type_life(particles_type[a], 3600, 3600)
part_type_alpha2(particles_type[a], 1, 0)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
a = (2 << 0)
particles_system[a] = part_system_create()
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1952, 0, 0, 1)
part_type_speed(particles_type[a], 3, 6, -0.15, 0)
part_type_life(particles_type[a], 3600, 3600)
part_type_direction(particles_type[a], 0, 360, 0, 0)
part_type_alpha3(particles_type[a], 1, 1, 0)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
particle_amount[a] = 400
a = (1 << 0)
particles_system[a] = part_system_create()
particles_type[a] = part_type_create()
part_system_depth(particles_system[a], -8500)
part_type_shape(particles_type[a], 10)
part_type_life(particles_type[a], 10, 20)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_color1(particles_type[a], 723856)
part_type_size(particles_type[a], 0.1, 0.15, 0.0025, 0)
part_type_alpha2(particles_type[a], 1, 0.25)
rain_counter = 0
rain_factor = 1
a = (3 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
part_system_depth(particles_system[a], -8500)
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1925, 0, 0, 1)
part_type_life(particles_type[a], 5, 40)
part_type_orientation(particles_type[a], 285, 285, 0, 0, 0)
part_type_direction(particles_type[a], 285, 285, 0, 0)
part_type_speed(particles_type[a], 10, 12, 0, 0)
part_type_scale(particles_type[a], 2, 0.75)
part_type_alpha1(particles_type[a], 0.6)
a = (4 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
part_system_depth(particles_system[a], -8500)
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1926, 1, 1, 0)
part_type_life(particles_type[a], 15, 15)
part_type_alpha2(particles_type[a], 1, 0.25)
a = (5 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
part_system_depth(particles_system[a], -8500)
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1925, 0, 0, 1)
part_type_life(particles_type[a], 5, 40)
part_type_orientation(particles_type[a], 285, 285, 0, 0, 0)
part_type_direction(particles_type[a], 285, 285, 0, 0)
part_type_speed(particles_type[a], 10, 12, 0, 0)
part_type_scale(particles_type[a], 2, 0.75)
part_type_alpha1(particles_type[a], 0.75)
part_type_color1(particles_type[a], 65373)
partciles_emitter[a] = part_emitter_create(particles_system[a])
a = (6 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
part_system_depth(particles_system[a], -8500)
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1926, 1, 1, 0)
part_type_life(particles_type[a], 15, 15)
part_type_alpha2(particles_type[a], 1, 0.25)
part_type_color1(particles_type[a], 65373)
a = (7 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_system_depth(particles_system[a], -8500)
part_type_sprite(particles_type[a], 1922, 1, 1, 0)
part_type_speed(particles_type[a], 0.2, 0.6, -0.02, 0)
part_type_direction(particles_type[a], 0, 360, 0, 0)
part_type_color3(particles_type[a], 16777215, 16769406, 11812613)
part_type_life(particles_type[a], 20, 25)
part_type_orientation(particles_type[a], 0, 360, 0, 15, 0)
part_type_alpha2(particles_type[a], 1, 0.25)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 10
a = (8 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_system_depth(particles_system[a], -8500)
part_type_sprite(particles_type[a], 1923, 1, 1, 0)
part_type_color3(particles_type[a], 16777215, 16044288, 11812613)
part_type_alpha2(particles_type[a], 1, 0.25)
part_type_life(particles_type[a], 5, 10)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 5
a = (9 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_system_depth(particles_system[a], -8500)
part_type_shape(particles_type[a], 2)
part_type_color3(particles_type[a], 16777215, 11812613, 16750929)
part_type_speed(particles_type[a], 0, 0, 0, 0)
part_type_alpha2(particles_type[a], 1, 0.25)
part_type_size(particles_type[a], 0.03, 0.06, -0.001, 0)
part_type_life(particles_type[a], 10, 20)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 0, 360, 0, 3)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 7
a = (12 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 10)
part_type_life(particles_type[a], 8, 12)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 65, 115, 0, 3)
part_type_speed(particles_type[a], 2, 2.5, 0, 0)
part_type_size(particles_type[a], 0.05, 0.2, 0, 0)
part_type_alpha2(particles_type[a], 1, 0.25)
part_type_color3(particles_type[a], 16777215, 4235519, 255)
part_type_blend(particles_type[a], 1)
particle_fire_amount = 5
a = (13 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 10)
part_type_life(particles_type[a], 90, 120)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 85, 95, 0, 3)
part_type_speed(particles_type[a], 0.01, 0.05, 0, 0)
part_type_size(particles_type[a], 0.075, 0.1, 0, 0)
part_type_alpha2(particles_type[a], 0.3, 0.05)
part_type_color3(particles_type[a], 65535, 4235519, 255)
part_type_blend(particles_type[a], 1)
a = (14 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 11)
part_type_life(particles_type[a], 90, 180)
part_type_orientation(particles_type[a], 0, 360, 0, 2, 0)
part_type_size(particles_type[a], 5, 7, 0, 0)
part_type_alpha3(particles_type[a], 0.005, 0.02, 0.005)
part_type_color2(particles_type[a], 4235519, 255)
particle_amount[a] = 1
a = (15 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 11)
part_type_life(particles_type[a], 150, 151)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_size(particles_type[a], 5, 7, 0, 0)
part_type_alpha3(particles_type[a], 0.02, 0.05, 0.02)
part_type_color2(particles_type[a], 32768, 3787971)
particle_amount[a] = 1
a = (16 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1928, 1, 1, 0)
part_type_life(particles_type[a], 10, 150)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 0, 0, 0, 0)
part_type_speed(particles_type[a], 0, 0, 0, 0)
part_type_size(particles_type[a], 1, 1, 0, 0)
part_type_alpha1(particles_type[a], 1)
part_type_color2(particles_type[a], 9043892, 32768)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 1
a = (17 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1924, 1, 1, 0)
part_type_life(particles_type[a], 25, 35)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 75, 105, 0, 0)
part_type_speed(particles_type[a], 1, 1.5, 0, 0)
part_type_gravity(particles_type[a], 0.05, 270)
part_type_size(particles_type[a], 0.5, 1, 0, 0)
part_type_alpha2(particles_type[a], 1, 0.75)
part_type_color2(particles_type[a], 32768, 3787971)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 1
a = (18 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1928, 1, 1, 0)
part_type_life(particles_type[a], 30, 45)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 30, 150, 0, 3)
part_type_gravity(particles_type[a], 0.05, 270)
part_type_speed(particles_type[a], 1.25, 1.5, -0.03, 0)
part_type_size(particles_type[a], 1, 1, -0.01, 0)
part_type_alpha2(particles_type[a], 1, 0.25)
part_type_color2(particles_type[a], 16777215, 32768)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 4
a = (19 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_system_depth(particles_system[a], -8500)
part_type_sprite(particles_type[a], 1923, 0, 1, 1)
part_type_speed(particles_type[a], 0.2, 0.6, -0.02, 0)
part_type_size(particles_type[a], 0.7, 1, -0.01, 0)
part_type_direction(particles_type[a], 0, 360, 0, 0)
part_type_color3(particles_type[a], 16777215, 16769406, 16725288)
part_type_life(particles_type[a], 20, 25)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_alpha2(particles_type[a], 1, 0.25)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 10
a = (21 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_system_depth(particles_system[a], -8500)
part_type_sprite(particles_type[a], 1920, 0, 0, 1)
part_type_life(particles_type[a], 15, 25)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 0, 360, 0, 0)
part_type_size(particles_type[a], 1, 1, 0, 0)
part_type_speed(particles_type[a], 0, 1, -0.2, 0)
part_type_alpha2(particles_type[a], 1, 0.25)
part_type_color3(particles_type[a], 65535, 4235519, 255)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 10
a = (22 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_system_depth(particles_system[a], -8500)
part_type_sprite(particles_type[a], 1920, 0, 0, 1)
part_type_life(particles_type[a], 45, 60)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 0, 360, 0, 0)
part_type_size(particles_type[a], 0.5, 1.5, 0, 0)
part_type_speed(particles_type[a], 0.5, 1, -0.15, 0)
part_type_alpha2(particles_type[a], 0.4, 0.1)
part_type_color3(particles_type[a], 3288643, 3288643, 3288643)
part_type_blend(particles_type[a], 0)
particle_amount[a] = 5
a = (24 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_system_depth(particles_system[a], -8500)
part_type_sprite(particles_type[a], 1921, 0, 0, 1)
part_type_life(particles_type[a], 60, 90)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 0, 360, 0, 0)
part_type_size(particles_type[a], 0.2, 1, 0, 0)
part_type_speed(particles_type[a], 2, 2.5, -0.15, 0)
part_type_alpha2(particles_type[a], 0.4, 0.1)
part_type_color3(particles_type[a], 65535, 4235519, 255)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 20
a = (23 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1920, 0, 0, 1)
part_type_life(particles_type[a], 15, 25)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 0, 360, 0, 0)
part_type_speed(particles_type[a], 0.1, 0.2, -0.01, 0)
part_type_size(particles_type[a], 1, 1, 0, 0)
part_type_alpha2(particles_type[a], 0.9, 0.5)
part_type_color3(particles_type[a], 65535, 34815, 255)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 3
a = (10 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 11)
part_type_life(particles_type[a], 2, 150)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 87, 93, 0, 3)
part_type_speed(particles_type[a], 0.1, 0.15, 0, 0)
part_type_size(particles_type[a], 0.1, 0.15, 0, 0.005)
part_type_alpha2(particles_type[a], 0.5, 0.15)
part_type_color3(particles_type[a], 8421504, 4210752, 0)
part_type_blend(particles_type[a], 0)
a = (11 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 11)
part_type_sprite(particles_type[a], 1920, 0, 0, 1)
part_type_life(particles_type[a], 1, 30)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 85, 95, 0, 3)
part_type_speed(particles_type[a], 0.05, 0.15, 0, 0)
part_type_size(particles_type[a], 0.5, 0.75, 0.002, 0)
part_type_alpha3(particles_type[a], 1, 0.75, 0.25)
part_type_color3(particles_type[a], 65535, 4235519, 255)
part_type_blend(particles_type[a], 1)
a = (30 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -50)
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1922, 0, 0, 1)
part_type_life(particles_type[a], 240, 360)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_size(particles_type[a], 0.8, 1, 0, 0)
part_type_alpha1(particles_type[a], 0.5)
part_type_blend(particles_type[a], 0)
a = (31 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 10)
part_type_life(particles_type[a], 5, 8)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_size(particles_type[a], 0.1, 0.15, 0, 0)
part_type_alpha2(particles_type[a], 1, 0.5)
part_type_color2(particles_type[a], 16777215, 65280)
part_type_blend(particles_type[a], 1)
a = (33 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 11)
part_type_life(particles_type[a], 360, 370)
part_type_orientation(particles_type[a], 0, 360, 0, 0.5, 0)
part_type_size(particles_type[a], 2, 3, 0, 0)
part_type_alpha3(particles_type[a], 0.01, 0.25, 0.1)
part_type_color2(particles_type[a], 16777215, 8421504)
particle_amount[a] = 1
a = (34 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 11)
part_type_life(particles_type[a], 360, 370)
part_type_orientation(particles_type[a], 0, 360, 0, 0.5, 0)
part_type_size(particles_type[a], 2, 3, 0, 0)
part_type_alpha3(particles_type[a], 0.1, 0.4, 0.1)
part_type_color1(particles_type[a], 65373)
particle_amount[a] = 1
a = (35 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1918, 0, 0, 1)
part_type_life(particles_type[a], 720, 960)
part_type_orientation(particles_type[a], 0, 360, 0, 0.5, 0)
part_type_speed(particles_type[a], 0.5, 1.8, 0, 0.05)
part_type_direction(particles_type[a], 345, 15, 0, 10)
part_type_size(particles_type[a], 0.5, 1, 0, 0)
part_type_alpha3(particles_type[a], 0.75, 1, 0.5)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 1
a = (36 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 10)
part_type_life(particles_type[a], 8, 12)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 65, 115, 0, 3)
part_type_speed(particles_type[a], 2, 2.5, 0, 0)
part_type_size(particles_type[a], 0.05, 0.2, 0, 0)
part_type_alpha2(particles_type[a], 1, 0.25)
part_type_color3(particles_type[a], 16777215, 8716203, 65280)
part_type_blend(particles_type[a], 0)
particle_amount[a] = 5
a = (37 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 10)
part_type_life(particles_type[a], 8, 12)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 0, 0, 0, 3)
part_type_size(particles_type[a], 0.1, 0.25, 0, 0)
part_type_alpha2(particles_type[a], 1, 0.25)
part_type_color2(particles_type[a], 8076888, 3678763)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 5
a = (38 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1927, 1, 1, 0)
part_type_life(particles_type[a], 15, 15)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 0, 360, 0, 0)
part_type_speed(particles_type[a], 0.1, 0.2, -0.03, 0)
part_type_size(particles_type[a], 0.8, 1, 0, 0)
part_type_alpha2(particles_type[a], 0.5, 0.3)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 1
a = (27 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1920, 0, 0, 1)
part_type_life(particles_type[a], 60, 120)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 85, 95, 0, 0)
part_type_speed(particles_type[a], 1, 1.5, -0.01, 0)
part_type_size(particles_type[a], 1.2, 1.5, 0.04, 0)
part_type_alpha2(particles_type[a], 0.9, 0.4)
part_type_color3(particles_type[a], 0, 4210752, 8421504)
part_type_blend(particles_type[a], 0)
a = (28 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1920, 0, 0, 1)
part_type_life(particles_type[a], 90, 150)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 85, 95, 0, 0)
part_type_speed(particles_type[a], 0.2, 0.5, 0, 0)
part_type_size(particles_type[a], 0.7, 1.3, 0.04, 0)
part_type_alpha2(particles_type[a], 0.9, 0.4)
part_type_color3(particles_type[a], 0, 4210752, 8421504)
part_type_blend(particles_type[a], 0)
a = (29 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1924, 0, 0, 1)
part_type_life(particles_type[a], 5, 10)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 85, 95, 0, 0)
part_type_speed(particles_type[a], 2, 2.5, -0.04, 0)
part_type_size(particles_type[a], 1, 1, -0.02, 0)
part_type_alpha2(particles_type[a], 0.9, 0.4)
part_type_color3(particles_type[a], 16777215, 65535, 8421504)
part_type_blend(particles_type[a], 1)
a = (39 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1920, 0, 0, 1)
part_type_life(particles_type[a], 60, 120)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 85, 95, 0, 0)
part_type_speed(particles_type[a], 0.2, 0.4, -0.01, 0)
part_type_gravity(particles_type[a], 0.01, 90)
part_type_size(particles_type[a], 0.5, 0.7, 0.001, 0)
part_type_alpha2(particles_type[a], 0.6, 0.2)
part_type_color3(particles_type[a], 16777215, 8421504, 4210752)
part_type_blend(particles_type[a], 0)
a = (25 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1920, 0, 0, 1)
part_type_life(particles_type[a], 15, 40)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_size(particles_type[a], 0.8, 1.1, -0.001, 0)
part_type_alpha2(particles_type[a], 1, 0.3)
part_type_color3(particles_type[a], 2237085, 2763361, 2565944)
part_type_blend(particles_type[a], 0)
a = (40 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 11)
part_type_sprite(particles_type[a], 1920, 0, 0, 1)
part_type_life(particles_type[a], 10, 30)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 85, 95, 0, 3)
part_type_speed(particles_type[a], 0.1, 0.3, 0, 0)
part_type_size(particles_type[a], 0.5, 0.75, -0.001, 0)
part_type_alpha3(particles_type[a], 1, 0.75, 0.25)
part_type_color3(particles_type[a], 65535, 4235519, 255)
part_type_blend(particles_type[a], 1)
a = (41 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_system_depth(particles_system[a], -8500)
part_type_shape(particles_type[a], 10)
part_type_life(particles_type[a], 60, 120)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 0, 360, 0, 0)
part_type_size(particles_type[a], 0.1, 0.2, 0.0005, 0)
part_type_speed(particles_type[a], 0.5, 1.5, -0.015, 0)
part_type_alpha2(particles_type[a], 1, 0.25)
part_type_color3(particles_type[a], 65535, 4235519, 255)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 10
a = (44 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1920, 0, 0, 1)
part_type_life(particles_type[a], 110, 150)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 85, 95, 0, 0)
part_type_speed(particles_type[a], 0.1, 0.3, -0.01, 0)
part_type_gravity(particles_type[a], 0.01, 90)
part_type_size(particles_type[a], 1, 1.5, 0.002, 0)
part_type_alpha2(particles_type[a], 0.6, 0.2)
part_type_color2(particles_type[a], 2575978, 8421504)
part_type_blend(particles_type[a], 0)
a = (42 << 0)
particles_system[a] = part_system_create()
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_system_depth(particles_system[a], -8500)
part_type_shape(particles_type[a], 12)
part_type_life(particles_type[a], 20, 50)
part_type_orientation(particles_type[a], 0, 360, 0, 1, 0)
part_type_direction(particles_type[a], 0, 360, 0, 0)
part_type_size(particles_type[a], 0.05, 0.15, 0.004, 0)
part_type_speed(particles_type[a], 0, 0, 0, 0)
part_type_alpha2(particles_type[a], 0.65, 0)
part_type_color2(particles_type[a], 12632256, 16777215)
part_type_blend(particles_type[a], 0)
particle_amount[a] = 3
a = (29 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 1924, 0, 0, 1)
part_type_life(particles_type[a], 5, 10)
part_type_orientation(particles_type[a], 0, 360, 0, 0, 0)
part_type_direction(particles_type[a], 85, 95, 0, 0)
part_type_speed(particles_type[a], 2, 2.5, -0.04, 0)
part_type_size(particles_type[a], 1, 1, -0.02, 0)
part_type_alpha2(particles_type[a], 0.9, 0.4)
part_type_color3(particles_type[a], 16777215, 65535, 8421504)
part_type_blend(particles_type[a], 1)
a = (45 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -8500)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_sprite(particles_type[a], 144, 1, 0, 0)
part_type_life(particles_type[a], 200, 230)
part_type_speed(particles_type[a], 2.7, 4.2, 0, 0.05)
part_type_direction(particles_type[a], 355, 5, 0, 0.75)
part_type_blend(particles_type[a], 0)
particle_amount[a] = 1
a = (46 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -9575)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 8)
part_type_life(particles_type[a], 80, 95)
part_type_orientation(particles_type[a], 0, 360, 0, 0.5, 0)
part_type_speed(particles_type[a], 8, 11, 0, 0.05)
part_type_direction(particles_type[a], -15, 15, 0, 6)
part_type_size(particles_type[a], 0.25, 0.5, 0, 0.05)
part_type_alpha1(particles_type[a], 1)
part_type_color2(particles_type[a], 15991039, 49407)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 1
a = (47 << 0)
particles_system[a] = part_system_create()
part_system_depth(particles_system[a], -9575)
partciles_emitter[a] = part_emitter_create(particles_system[a])
particles_type[a] = part_type_create()
part_type_shape(particles_type[a], 10)
part_type_life(particles_type[a], 80, 85)
part_type_orientation(particles_type[a], 0, 360, 0, 0.5, 0)
part_type_size(particles_type[a], 2.5, 3.8, 0, 0.05)
part_type_speed(particles_type[a], 8, 8, 0, 0)
part_type_direction(particles_type[a], -5, 5, 0, 0.5)
part_type_alpha1(particles_type[a], 0.95)
part_type_color1(particles_type[a], 13122486)
part_type_blend(particles_type[a], 1)
particle_amount[a] = 1
