function lista_base() //gml_Script_lista_base
{
    global.sl_hover = -1
    global.sl_selected = -1
    global.sl_w = 32
    var a = (0 << 0)
    global.sl_id[a] = a
    global.sl_name[a] = "Slot 1"
    global.sl_free[a] = 2
    global.sl_base_id[a] = (1 << 0)
    global.sl_x[a] = 149
    global.sl_y[a] = 68
    a = (1 << 0)
    global.sl_id[a] = a
    global.sl_name[a] = "Slot 2"
    global.sl_free[a] = 0
    global.sl_base_id[a] = -1
    global.sl_x[a] = 149
    global.sl_y[a] = 135
    a = (2 << 0)
    global.sl_id[a] = a
    global.sl_name[a] = "Slot 3"
    global.sl_free[a] = 0
    global.sl_base_id[a] = -1
    global.sl_x[a] = 149
    global.sl_y[a] = 172
    a = (3 << 0)
    global.sl_id[a] = a
    global.sl_name[a] = "Slot 4"
    global.sl_free[a] = 0
    global.sl_base_id[a] = -1
    global.sl_x[a] = 107
    global.sl_y[a] = 68
    a = (4 << 0)
    global.sl_id[a] = a
    global.sl_name[a] = "Slot 5"
    global.sl_free[a] = 0
    global.sl_base_id[a] = -1
    global.sl_x[a] = 68
    global.sl_y[a] = 68
    a = (5 << 0)
    global.sl_id[a] = a
    global.sl_name[a] = "Slot 6"
    global.sl_free[a] = 0
    global.sl_base_id[a] = -1
    global.sl_x[a] = 107
    global.sl_y[a] = 172
    a = (6 << 0)
    global.sl_id[a] = a
    global.sl_name[a] = "Slot 7"
    global.sl_free[a] = 0
    global.sl_base_id[a] = -1
    global.sl_x[a] = 68
    global.sl_y[a] = 172
    global.info_base = "Modules are used to obtain passive bonuses.\nOnce the module is installed it will be at level 0.\nTo increase its level and acquire bonuses you must craft the corresponding kit at the workbench.\nYou can uninstall a module whenever you want but the materials needed to build it will not be refunded."
    global.base_install_w = 96
    global.base_install_h = 16
    global.base_install_x = 299
    global.base_install_y = (40 + (global.base_install_h / 2))
    global.base_hover = -1
    global.base_selected = -1
    global.base_name_x = 318
    global.base_name_y = 48
    global.base_current_bonus_y = 64
    global.base_next_bonus_y = 135
    global.base_installing_now = 0
    global.base_installing_max = 90
    global.base_slider = 0
    global.base_slider_time_max = 6
    global.base_slider_base_id = -1
    a = (0 << 0)
    global.base_id[a] = a
    global.base_name[a] = "Infirmary"
    global.base_sprite[a] = s_pda_base_med_station
    global.base_lvl[a] = 0
    global.base_lvl_max[a] = 2
    global.base_x[a] = 248
    global.base_y[a] = 63
    global.base_w[a] = sprite_get_width(global.base_sprite[a])
    global.base_h[a] = sprite_get_height(global.base_sprite[a])
    global.base_des_general[a] = "Allow cafting medication and grants passive bonus to increase overall health"
    global.base_des[a][0] = "Increase max HP, less chance of bleeding,\ngradually restore HP."
    global.base_des[a][1] = "Increase max HP, less chance of bleeding,\ngradually restore HP."
    a = (1 << 0)
    global.base_id[a] = a
    global.base_name[a] = "Storage"
    global.base_sprite[a] = s_pda_base_storage
    global.base_lvl[a] = 0
    global.base_lvl_max[a] = 2
    global.base_x[a] = 213
    global.base_y[a] = 63
    global.base_w[a] = sprite_get_width(global.base_sprite[a])
    global.base_h[a] = sprite_get_height(global.base_sprite[a])
    global.base_des_general[a] = "Provide more chest to store items"
    global.base_des[a][0] = "+1 Personal chest"
    global.base_des[a][1] = "+1 Personal chest"
    a = (2 << 0)
    global.base_id[a] = a
    global.base_name[a] = "Bedroom"
    global.base_sprite[a] = s_pda_base_bed
    global.base_lvl[a] = 0
    global.base_lvl_max[a] = 2
    global.base_x[a] = 283
    global.base_y[a] = 63
    global.base_w[a] = sprite_get_width(global.base_sprite[a])
    global.base_h[a] = sprite_get_height(global.base_sprite[a])
    global.base_des_general[a] = "Comfortable bed that heal your wound while sleeping.\nYour skills will level up faster"
    global.base_des[a][0] = "10% more experience.\nRecover fatigue and injuries 50% faster"
    global.base_des[a][1] = "20% more experience.\nRecover fatigue and injuries 100% faster"
    a = (4 << 0)
    global.base_id[a] = a
    global.base_name[a] = "Kitchen"
    global.base_sprite[a] = s_pda_base_kitchen
    global.base_lvl[a] = 0
    global.base_lvl_max[a] = 2
    global.base_x[a] = 318
    global.base_y[a] = 63
    global.base_w[a] = sprite_get_width(global.base_sprite[a])
    global.base_h[a] = sprite_get_height(global.base_sprite[a])
    global.base_des_general[a] = "Good nutrition is essential.\nThis kitchen allows to cook scrap food into more beneficial meals"
    global.base_des[a][0] = "Allows cooking basic meals"
    global.base_des[a][1] = "Allows cooking all meals"
    a = (5 << 0)
    global.base_id[a] = a
    global.base_name[a] = "Recycling center"
    global.base_sprite[a] = s_pda_base_recycling
    global.base_lvl[a] = 0
    global.base_lvl_max[a] = 2
    global.base_x[a] = 353
    global.base_y[a] = 63
    global.base_w[a] = sprite_get_width(global.base_sprite[a])
    global.base_h[a] = sprite_get_height(global.base_sprite[a])
    global.base_des_general[a] = "Nothing is wasted! Gain more materials when you scrap them"
    global.base_des[a][0] = "+15% scrapped items"
    global.base_des[a][1] = "+30% scrapped items"
    a = (6 << 0)
    global.base_id[a] = a
    global.base_name[a] = "Gym"
    global.base_sprite[a] = s_pda_base_gym
    global.base_lvl[a] = 0
    global.base_lvl_max[a] = 2
    global.base_x[a] = 213
    global.base_y[a] = 98
    global.base_w[a] = sprite_get_width(global.base_sprite[a])
    global.base_h[a] = sprite_get_height(global.base_sprite[a])
    global.base_des_general[a] = "A small gym where you can work out.\nGrants more stamina and cardio experience rate"
    global.base_des[a][0] = "+10 stamina.\n+20% cardio experience rate"
    global.base_des[a][1] = "+20 stamina.\n+40% cardio experience rate"
    a = (7 << 0)
    global.base_id[a] = a
    global.base_name[a] = "Shooting range"
    global.base_sprite[a] = s_pda_base_shooting
    global.base_lvl[a] = 0
    global.base_lvl_max[a] = 2
    global.base_x[a] = 248
    global.base_y[a] = 98
    global.base_w[a] = sprite_get_width(global.base_sprite[a])
    global.base_h[a] = sprite_get_height(global.base_sprite[a])
    global.base_des_general[a] = "Train your shooting skill.\nGain more weapon damage and shooting experience rate"
    global.base_des[a][0] = "+5% weapon damage.\n+20% shooting experience rate"
    global.base_des[a][1] = "+10% weapon damage.\n+40% shooting experience rate"
    a = (3 << 0)
    global.base_id[a] = a
    global.base_name[a] = "Radio station"
    global.base_sprite[a] = s_pda_base_radio
    global.base_lvl[a] = 0
    global.base_lvl_max[a] = 2
    global.base_x[a] = 283
    global.base_y[a] = 98
    global.base_w[a] = sprite_get_width(global.base_sprite[a])
    global.base_h[a] = sprite_get_height(global.base_sprite[a])
    global.base_des_general[a] = "in development - do not install"
    global.base_des[a][0] = "Allows to see all the minimap"
    global.base_des[a][1] = "Show intresting points and chests on the minimap"
    a = (8 << 0)
    global.base_id[a] = a
    global.base_name[a] = "Forge"
    global.base_sprite[a] = s_pda_base_forge
    global.base_lvl[a] = 0
    global.base_lvl_max[a] = 2
    global.base_x[a] = 318
    global.base_y[a] = 98
    global.base_w[a] = sprite_get_width(global.base_sprite[a])
    global.base_h[a] = sprite_get_height(global.base_sprite[a])
    global.base_des_general[a] = "Provide scrap items every day"
    global.base_des[a][0] = "Provide some scrap items every day"
    global.base_des[a][1] = "Provide some scrap items every day"
    a = (9 << 0)
    global.base_id[a] = a
    global.base_name[a] = "Scavenger"
    global.base_sprite[a] = s_pda_base_scav
    global.base_lvl[a] = 0
    global.base_lvl_max[a] = 2
    global.base_x[a] = 353
    global.base_y[a] = 98
    global.base_w[a] = sprite_get_width(global.base_sprite[a])
    global.base_h[a] = sprite_get_height(global.base_sprite[a])
    global.base_des_general[a] = "Gives away random items every day"
    global.base_des[a][0] = "Gives away random items every day"
    global.base_des[a][1] = "Gives away random items every day"
    a = (10 << 0)
    global.base_id[a] = a
    global.base_name[a] = "Garden"
    global.base_sprite[a] = s_pda_base_garden
    global.base_lvl[a] = 0
    global.base_lvl_max[a] = 2
    global.base_x[a] = 213
    global.base_y[a] = 133
    global.base_w[a] = sprite_get_width(global.base_sprite[a])
    global.base_h[a] = sprite_get_height(global.base_sprite[a])
    global.base_des_general[a] = "Grows scrap food and scrap medicine, provides a small amount every day"
    global.base_des[a][0] = "20 scrap food and 10 scrap medicine"
    global.base_des[a][1] = "40 scrap food and 25 scrap medicine"
    a = (11 << 0)
    global.base_id[a] = a
    global.base_name[a] = "Ammo producer"
    global.base_sprite[a] = s_pda_base_ammo
    global.base_lvl[a] = 0
    global.base_lvl_max[a] = 2
    global.base_x[a] = 248
    global.base_y[a] = 133
    global.base_w[a] = sprite_get_width(global.base_sprite[a])
    global.base_h[a] = sprite_get_height(global.base_sprite[a])
    global.base_des_general[a] = "Provide scrap ammo every day and allows you to craft ammunition"
    global.base_des[a][0] = "30 scrap ammo every day and allows you to craft ammunition"
    global.base_des[a][1] = "50 scrap ammo every day and get 30% more ammunition from crafting"
    a = (12 << 0)
    global.base_id[a] = a
    global.base_name[a] = "Workshop"
    global.base_sprite[a] = s_pda_base_workshop
    global.base_lvl[a] = 0
    global.base_lvl_max[a] = 2
    global.base_x[a] = 283
    global.base_y[a] = 133
    global.base_w[a] = sprite_get_width(global.base_sprite[a])
    global.base_h[a] = sprite_get_height(global.base_sprite[a])
    global.base_des_general[a] = "You can repair weapons and armor by yourself"
    global.base_des[a][0] = "You can repair weapons and armor by yourself"
    global.base_des[a][1] = "Repair costs 50% less"
    ini_open(global.save_general)
    for (var i = 0; i < array_length_1d(global.base_id); i++)
    {
        var get_id = global.base_id[i]
        var k = 0
        if (get_id == (1 << 0))
            k = 0
        global.base_lvl[get_id] = ini_read_real("Base", string(get_id), k)
    }
    for (i = 0; i < array_length_1d(global.sl_id); i++)
    {
        get_id = global.sl_id[i]
        k = -1
        var kk = 0
        if (get_id == (0 << 0))
        {
            k = (1 << 0)
            kk = 2
        }
        global.sl_base_id[get_id] = ini_read_real("Base slot", string(get_id), k)
        global.sl_free[get_id] = ini_read_real("Base slot occupato", string(get_id), kk)
    }
    ini_close()
    return;
}

