function scr_b_quest_missing_group_1(argument0, argument1) //gml_Script_scr_b_quest_missing_group_1
{
    var xx = argument0
    var yy = argument1
    var o = obj_map_generator
    ds_grid_set(grid_floor2, (xx + 2), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 2), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 3), (yy + 9), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 5), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 9), 0)
    ds_grid_set(grid_floor2, (xx + 4), (yy + 10), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 5), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 9), 0)
    ds_grid_set(grid_floor2, (xx + 5), (yy + 10), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 5), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 9), 0)
    ds_grid_set(grid_floor2, (xx + 6), (yy + 10), 0)
    ds_grid_set(grid_floor2, (xx + 7), (yy + 5), 0)
    ds_grid_set(grid_floor2, (xx + 7), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 7), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 7), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 7), (yy + 9), 0)
    ds_grid_set(grid_floor2, (xx + 7), (yy + 10), 0)
    ds_grid_set(grid_floor2, (xx + 8), (yy + 5), 0)
    ds_grid_set(grid_floor2, (xx + 8), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 8), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 8), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 8), (yy + 9), 0)
    ds_grid_set(grid_floor2, (xx + 8), (yy + 10), 0)
    ds_grid_set(grid_floor2, (xx + 8), (yy + 11), 0)
    ds_grid_set(grid_floor2, (xx + 9), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 9), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 9), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 9), (yy + 9), 0)
    ds_grid_set(grid_floor2, (xx + 9), (yy + 10), 0)
    ds_grid_set(grid_floor2, (xx + 9), (yy + 11), 0)
    ds_grid_set(grid_floor2, (xx + 10), (yy + 6), 0)
    ds_grid_set(grid_floor2, (xx + 10), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 10), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 10), (yy + 9), 0)
    ds_grid_set(grid_floor2, (xx + 10), (yy + 10), 0)
    ds_grid_set(grid_floor2, (xx + 11), (yy + 7), 0)
    ds_grid_set(grid_floor2, (xx + 11), (yy + 8), 0)
    ds_grid_set(grid_floor2, (xx + 11), (yy + 9), 0)
    ds_grid_set(grid_floor2, (xx + 12), (yy + 7), 0)
    tilemap_set(o.layer_tileset_wall_below_indoor, 564, (xx + 2), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 528, (xx + 2), (yy + 12))
    tilemap_set(o.layer_tileset_wall_below_indoor, 529, (xx + 4), (yy + 3))
    tilemap_set(o.layer_tileset_wall_below_indoor, 596, (xx + 4), (yy + 7))
    tilemap_set(o.layer_tileset_wall_below_indoor, 566, (xx + 5), (yy + 6))
    tilemap_set(o.layer_tileset_wall_below_indoor, 530, (xx + 5), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 598, (xx + 5), (yy + 10))
    tilemap_set(o.layer_tileset_wall_below_indoor, 598, (xx + 7), (yy + 8))
    tilemap_set(o.layer_tileset_wall_below_indoor, 564, (xx + 8), (yy + 5))
    tilemap_set(o.layer_tileset_wall_below_indoor, 565, (xx + 8), (yy + 7))
    tilemap_set(o.layer_tileset_wall_below_indoor, 597, (xx + 10), (yy + 7))
    tilemap_set(o.layer_tileset_wall_below_indoor, 565, (xx + 10), (yy + 10))
    tilemap_set(o.layer_tileset_wall_below_indoor, 529, (xx + 12), (yy + 11))
    tilemap_set(o.layer_tileset_wall_below_indoor, 529, (xx + 13), (yy + 4))
    instance_create_depth(((xx * 16) + 103), ((yy * 16) + 119), 0, obj_quest_approach_missing_group_1)
    return;
}

