function lista_skill_2() //gml_Script_lista_skill_2
{
    global.sk_hover = -1
    global.sk_selected = -1
    global.sk_spec_hover = -1
    global.sk_spec_selected = -1
    global.sk_upgrading = 0
    global.sk_startx = 67
    global.sk_starty = 42
    global.sk_button_w = 85
    global.sk_button_h = 20
    global.sk_hud_hover_alpha = 0
    global.sk_hud_hover_alpha_factor = 1
    global.sk_des_x = (global.sk_startx + 110)
    global.sk_des_w = 208
    global.sk_spec_h = 50
    global.sk_unlocking_now = 0
    global.sk_unlocking_max = 90
    global.rate_cardio = 0.000043
    global.rate_shooting = 0.0005
    global.rate_style = 0.008
    global.rate_charisma = 0.00007
    var a = (0 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = global.sk_starty
    global.sk_name[a] = "Fitness"
    global.sk_des[a] = "Increase your physical stats"
    global.sk_des_value[a] = "+2 stamina per level"
    global.sk_lvl[a] = 0
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 1
    global.sk_id_skill_required[a] = -1
    global.sk_factor[a] = 1
    global.sk_upgrade[a][0] = (1 << 0)
    global.sk_upgrade[a][1] = (2 << 0)
    global.sk_upgrade[a][2] = (3 << 0)
    a = (1 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = global.sk_starty
    global.sk_name[a] = "Jogger"
    global.sk_des[a] = "Increase stamina and running does not cost stamina if you are under a certain weight"
    global.sk_des_value[a] = "+10 +2 stamina per level \nFree run under 20 + 2 per level kg"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (0 << 0)
    global.sk_factor[a] = 1
    a = (2 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = global.sk_starty
    global.sk_name[a] = "Mule"
    global.sk_des[a] = "Greatly increase your max weight"
    global.sk_des_value[a] = "+5 +0.6 max carry weight per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (0 << 0)
    global.sk_factor[a] = 1
    a = (3 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = global.sk_starty
    global.sk_name[a] = "Sprinter"
    global.sk_des[a] = "Slightly increase stamina and running speed and reduce running cost"
    global.sk_des_value[a] = "+5 +1 stamina per level \n+10% +3% running speed per level \n-30% -2% running cost per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (0 << 0)
    global.sk_factor[a] = 1
    a = (4 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 1))
    global.sk_name[a] = "Style"
    global.sk_des[a] = "Increase your looting speed"
    global.sk_des_value[a] = "+3% looting speed per level"
    global.sk_lvl[a] = 0
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 1
    global.sk_id_skill_required[a] = -1
    global.sk_factor[a] = 1
    global.sk_upgrade[a][0] = (5 << 0)
    global.sk_upgrade[a][1] = (6 << 0)
    global.sk_upgrade[a][2] = (7 << 0)
    a = (5 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 1))
    global.sk_name[a] = "Loot Goblin"
    global.sk_des[a] = "Greatly increase Looting speed.\nCan see chest through walls.\nSlightly more loot in chests."
    global.sk_des_value[a] = "+30% + 3% looting speed per level \n20% +2% more loot in chest per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (4 << 0)
    global.sk_factor[a] = 1
    a = (6 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 1))
    global.sk_name[a] = "Stealth"
    global.sk_des[a] = "Decrease enemies' sight range.\nEnemies take longer to detect you.\nMore damage while not detected."
    global.sk_des_value[a] = "-10% -1% enemies sight range per level.\n100% +5% detection time per level.\n+10% +2% damage while not detected per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (4 << 0)
    global.sk_factor[a] = 1
    a = (7 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 1))
    global.sk_name[a] = "Scout"
    global.sk_des[a] = "Slightly Looting speed.\nEnemies are visible for a longer time.\nMore hidden stash on maps."
    global.sk_des_value[a] = "10% +2% looting speed per level.\n20% +3% time enemies are visible.\n+30% +2% more hidden chest per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (4 << 0)
    global.sk_factor[a] = 1
    a = (8 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 2))
    global.sk_name[a] = "Shooting"
    global.sk_des[a] = "Increase your shooting abilities"
    global.sk_des_value[a] = "-2% recoil per level.\n+1% reloading speed per level"
    global.sk_lvl[a] = 0
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 1
    global.sk_id_skill_required[a] = -1
    global.sk_factor[a] = 1
    global.sk_upgrade[a][0] = (9 << 0)
    global.sk_upgrade[a][1] = (10 << 0)
    global.sk_upgrade[a][2] = (11 << 0)
    a = (9 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 2))
    global.sk_name[a] = "Operator"
    global.sk_des[a] = "Greatly reduce recoil and slightly increase reloading speed"
    global.sk_des_value[a] = "-15% -2% recoil per level.\n+5% +1% reloading speed per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (8 << 0)
    global.sk_factor[a] = 1
    a = (10 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 2))
    global.sk_name[a] = "Fast Hands"
    global.sk_des[a] = "Greatly increase reloading speed and slightly decrease recoil"
    global.sk_des_value[a] = "-5% -1% recoil per level.\n+20% +2% reloading speed per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (8 << 0)
    global.sk_factor[a] = 1
    a = (11 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 2))
    global.sk_name[a] = "Sniper"
    global.sk_des[a] = "Greatly increase ergonomic while aiming.\nGreatly increase damage while aiming"
    global.sk_des_value[a] = "+100% +10% ergonomic while aiming per level.\n+50% +8% damage while aiming per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (8 << 0)
    global.sk_factor[a] = 1
    a = (12 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 3))
    global.sk_name[a] = "Charisma"
    global.sk_des[a] = "Better deals with vendors"
    global.sk_des_value[a] = "+1% selling price per level.\n+2% traders money per level."
    global.sk_lvl[a] = 0
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 1
    global.sk_id_skill_required[a] = -1
    global.sk_factor[a] = 1
    global.sk_upgrade[a][0] = (13 << 0)
    global.sk_upgrade[a][1] = (14 << 0)
    global.sk_upgrade[a][2] = (15 << 0)
    a = (13 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 3))
    global.sk_name[a] = "Charm"
    global.sk_des[a] = "Traders have more roubles"
    global.sk_des_value[a] = "Traders have +50% +6& roubles per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (12 << 0)
    global.sk_factor[a] = 1
    a = (14 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 3))
    global.sk_name[a] = "Storage"
    global.sk_des[a] = "Traders have more of the items they sell"
    global.sk_des_value[a] = "Traders have 50% + 5% more items per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (12 << 0)
    global.sk_factor[a] = 1
    a = (15 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 3))
    global.sk_name[a] = "Workaholic"
    global.sk_des[a] = "Increase the rewards from quests"
    global.sk_des_value[a] = "+30% + 3% per level quest reward"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 10
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (12 << 0)
    global.sk_factor[a] = 1
    a = (16 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 4))
    global.sk_name[a] = "Medicine"
    global.sk_des[a] = "Allows you to craft more medication based on level if you have an infirmary"
    global.sk_des_value[a] = ""
    global.sk_lvl[a] = 0
    global.sk_lvl_max[a] = 5
    global.sk_base[a] = 1
    global.sk_id_skill_required[a] = -1
    global.sk_factor[a] = 1
    global.sk_upgrade[a][0] = (17 << 0)
    global.sk_upgrade[a][1] = (18 << 0)
    a = (17 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 4))
    global.sk_name[a] = "Field medic"
    global.sk_des[a] = "Decrease medication usage time"
    global.sk_des_value[a] = "-40% -6% medication usage time per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 5
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (16 << 0)
    global.sk_factor[a] = 1
    a = (18 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 4))
    global.sk_name[a] = "Pharmacist"
    global.sk_des[a] = "Allows you to craft injectors based on level if you have an infirmary"
    global.sk_des_value[a] = ""
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 5
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (16 << 0)
    global.sk_factor[a] = 1
    a = (22 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 5))
    global.sk_name[a] = "Gunsmith"
    global.sk_des[a] = "Allows you to craft ammunition(Ammo producer tier 1 requiered) and repair kit based on the level"
    global.sk_des_value[a] = ""
    global.sk_lvl[a] = 0
    global.sk_lvl_max[a] = 5
    global.sk_base[a] = 1
    global.sk_id_skill_required[a] = -1
    global.sk_factor[a] = 1
    global.sk_upgrade[a][0] = (23 << 0)
    global.sk_upgrade[a][1] = (24 << 0)
    a = (23 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 5))
    global.sk_name[a] = "Modder"
    global.sk_des[a] = "Mounted mods are more effective"
    global.sk_des_value[a] = "+10% + 2% effectivness of mounted mod per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 5
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (22 << 0)
    global.sk_factor[a] = 1
    a = (24 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 5))
    global.sk_name[a] = "Gear lover"
    global.sk_des[a] = "Greatly Decrease the durability loss for weapons and armor"
    global.sk_des_value[a] = "-20% -5% weapons and armors durability loss per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 5
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (22 << 0)
    global.sk_factor[a] = 1
    a = (19 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 6))
    global.sk_name[a] = "Cooking"
    global.sk_des[a] = "Learn new recipes to cook in the kitchen and slightly increase the nutritional value of the foods you create"
    global.sk_des_value[a] = "+3% nutrition from your cooked meals per level"
    global.sk_lvl[a] = 0
    global.sk_lvl_max[a] = 5
    global.sk_base[a] = 1
    global.sk_id_skill_required[a] = -1
    global.sk_factor[a] = 1
    global.sk_upgrade[a][0] = (20 << 0)
    global.sk_upgrade[a][1] = (21 << 0)
    a = (20 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 6))
    global.sk_name[a] = "Chef"
    global.sk_des[a] = "Learn more recipes and greatly increase the nutritional value of the foods you create"
    global.sk_des_value[a] = "+30% +5% nutrition from your cooked meals per level"
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 5
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (19 << 0)
    global.sk_factor[a] = 1
    a = (21 << 0)
    global.sk_id[a] = a
    global.sk_y[a] = (global.sk_starty + (global.sk_button_h * 6))
    global.sk_name[a] = "Nutritionist"
    global.sk_des[a] = "When you're not starving or dehydrated you get more health and stamina"
    global.sk_des_value[a] = "+10 +2 hp per level.\n+15 +2 stamina per level."
    global.sk_lvl[a] = -1
    global.sk_lvl_max[a] = 5
    global.sk_base[a] = 0
    global.sk_id_skill_required[a] = (19 << 0)
    global.sk_factor[a] = 1
    ini_open(global.save_general)
    var quante_skill = array_length_1d(global.sk_id)
    for (var i = 0; i < quante_skill; i++)
    {
        var iid = global.sk_id[i]
        global.sk_lvl[iid] = ini_read_real("skill", string(iid), global.sk_lvl[iid])
        global.sk_last_level[i] = ini_read_real("skill last level", string(iid), -1)
    }
    ini_close()
    return;
}

